### ISSUE TITLE
Aws::DynamoDB::Errors::ValidationException

### ISSUE THREAD

**Issue by archonic** [Dynamoid/Dynamoid#107]
```
Aws::DynamoDB::Errors::ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string
```

It looks like this is something Dynamoid could take care of in house. A nil or empty attribute should be omitted.

Update: I've taken a closer look and it looks as if something like `DynamoidModel.new(whatever: nil, another: "")` isn't a problem. I'll have to dig deeper to see what's causing this issue.

Another update: It's specifically a `where(..).any?` causing this. I have a `duplicate?` method which can end up running something like this:

```
NotificationEventEmail.where(notification_generator_id: 1, event_status: 'send', num_dispatch_attempts: 0, recipient: "someone@example.com", subject: "").any?
```

That can be fixed with something that removed blank attributes like this:

```
NotificationEventEmail.where({notification_generator_id: 1, event_status: 'send', num_dispatch_attempts: 0, recipient: "someone@example.com", subject: ""}.delete_if { |k, v| v.blank? }).any?
```

But I think seeing as this is a quirk of the AWS SDK, this should be done by Dynamoid like it does for inserts.

**Comment by pboling** [comment]
@archonic Can you check to see if this is still a problem?  We have done a lot of work improving dynamoid recently.

**Comment by ghiculescu** [comment]
for reference, this is a problem with Dynamo - https://news.ycombinator.com/item?id=13170746

**Comment by archonic** [comment]
@pboling Sorry, I changed jobs and no longer have access to the code base I was working with.

**Comment by andrykonchin** [comment]
@pboling for the reference this issue should be already fixed.

At least for document creating/updating.  We replace empty sets and strings with `nil`.

https://github.com/Dynamoid/Dynamoid/blob/master/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L427-L430

I touched this logic recently https://github.com/Dynamoid/Dynamoid/commit/c3145c585153ddcbda2001ec0809332a1caf36b1

**Comment by pboling** [comment]
We can reopen if someone reports it anew.

**Comment by yoonwaiyan** [comment]
@pboling is empty string acceptable in `import` method? I'm trying to port over ActiveRecord rows to use DynamoDB but no luck with the same error message.

**Comment by andrykonchin** [comment]
@yoonwaiyan It isn't implemented. Good catch! Will fix it soon.

**Comment by mmhan** [comment]
@pboling Empty string is still an issue. Here's an example.

```
class Event
  include Dynamoid::Document

  field :meta, :raw
end

Event.create(meta: { hello: "" }) # this will raise empty string error.
```

Any workaround for that?

**Comment by andrykonchin** [comment]
@mmhan 

Good catch 👍 . We missed this case.
No, there is no workaround here except manual removing empty strings and sets.
We will fix it ASAP.

**Comment by andrykonchin** [comment]
@mmhan Fixed. Please check master branch.

**Comment by mmhan** [comment]
Awesome! 🙌
