### ISSUE TITLE
Why no nesting of models in Dynamoid?

### ISSUE THREAD

**Issue by everett-wetchler** [Dynamoid/Dynamoid#112]
As I see it, the main advantage of DynamoDB (and Mongo and other document databases) is to be able to nest models in documents. E.g., to have a Person table with string fields like "name" but also fields like "address" which may itself be an object with "street" and "city" and "zip" etc.

Why does Dynamoid spread them into separate tables with foreign keys, effectively relationalizing a document database?

Best,

E

**Comment by pboling** [comment]
This is just one way to wrap DynamoDB.  People use DynamoDB to store all kinds of different information.  In my projects I do not nest models in documents within Dynamo, or at least not in models that use DynamoDB, but I do access DynamoDB via other methods for other use cases.  This helps people map a specific use case onto DynamoDB.  I don't even use the foreign keys.  I just use it for the ease of auto-table creation, auto-schema updating, and DSL around the APIs for indexing, batching, and querying.
