### ISSUE TITLE
Rails 5 support + ActiveRecord associations?

### ISSUE THREAD

**Issue by 1kevinxu1** [Dynamoid/Dynamoid#113]
Hi, I'm a new developer so I'm not sure if this is the best place to ask these questions, let me know if I should move this somewhere else. I'm running a small project in Rails 5 and would like to use Dynamoid, and I saw that support was in the works. Is there any estimate on when that version will be released?

Also, when I assign associations in Dynamoid, is there any built in way to assign ddb documents to ActiveRecord objects? For example, if I am using dynamo to build a new feature for user's posts (comments, photos, videos, etc.) is there a way for me to assign each document in a way where I can call @user.posts and receive an array of Dynamoid objects with foreign keys of user_ids? Is it as simple as defining belongs_to and has_many in the models respectively, even if Users are stored in mysql?

**Comment by pboling** [comment]
> Is there any estimate on when that version will be released?

No.  But, you can test out Rails 5 support by pointing to master.  This gem is not so widely used that you can wait for others to test Rails 5 and wait on a release, so I recommend doing that yourself, and reporting back if successful or not.

Hopefully it will be released soon.  I don't think any of the maintainers use Rails 5 on any projects yet, so support and testing has all been from the community.

> any built in way to assign ddb documents to ActiveRecord objects?

I do not think so.  This gem will associate "foreign keys" between models that are Dynamoid models, as you can see in the Readme.  I do not think it can handle cross ORM associations, so you would have to implement something yourself.

> Is it as simple as defining belongs_to and has_many in the models respectively, even if Users are stored in mysql?

No.  The way I do this myself is I have a method on my regular AR models that does a lookup using queries on the Dynamoid models, and I store the keys, or unique lookup values in the Dynamoid models that links them back to the regular AR models.

**Comment by 1kevinxu1** [comment]
Ok! Thank you for your quick response, it's very much appreciated. Just a silly follow up question—what do you mean by pointing to master? Do you mean forking the gem?

**Comment by pboling** [comment]
Your project has a `Gemfile`.  In there you can specify dependencies on the `HEAD` version of gems, to use the latest, unreleased, code.

For example:
```
gem "dynamoid", git: "https://github.com/Dynamoid/Dynamoid.git", branch: "master"
```

**Comment by pboling** [comment]
Closing this, Rails 5 is now supported.
