### ISSUE TITLE
"Foreign key" for associations

### ISSUE THREAD

**Issue by xkraty** [Dynamoid/Dynamoid#114]
I have a problem with relations, I'm migrating an app from node to rails, unfortunately I didn't make it so naming are not really standard; I have a model Release and a model Artist

```
class Release
  include Dynamoid::Document

  belongs_to :artists, class: Artist

  field :_id
  field :title

end
```

```
class Artist
  include Dynamoid::Document

  has_many :releases, class_name: :release

  field :_id
  field :name

end
```

The problem is that my relation field in Release is named artists instead of artists_id so i can't get it to work; it would be the foreign_key field but I'm not understanding how to do it here, I gave a look at the library but I'm not so advanced.

Thanks in advance
Chris

**Comment by pboling** [comment]
That's a part of this project I am not familiar with.  @bglusman any idea?

**Comment by andrykonchin** [comment]
Implemented. So `foreign_key` option can be used in the following way

```ruby
belongs_to :artists, class: Artist, foreign_key: :artists
```
