### ISSUE TITLE
Default values does not seem to work for :serialized fields

### ISSUE THREAD

**Issue by NielsKSchjoedt** [Dynamoid/Dynamoid#117]
```ruby
field :my_hash, :serialized, { default: {} }
```

doesn't work

**Comment by pboling** [comment]
@xdougx There is at least one PR that attempts to address issues with serialization.  None of them has been accepted yet, and all are failing the build and are waiting on someone to rebase them on latest master (master build is green again!)

**Comment by pboling** [comment]
@NielsKSchjoedt This is fixed in latest master.
