### ISSUE TITLE
How do you batch save objects?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [Dynamoid/Dynamoid#118]
I can see that `batch_write_items` was incorporated recently. I can't seem to figure out though, what would be the way to batch persist an array of objects?

```ruby
class Item
  include Dynamoid::Document

  field :my_attr
end

[Item.new(my_attr: 'a'), Item.new(my_attr: 'b'), Item.new(my_attr: 'c')] # Call what?
```

**Comment by pboling** [comment]
```
      # NOTE: DynamoDB's PutItem API allows MAXIMUM of 25 items per request,
      #             but splitting into groups of 5 for this example
      data_array.in_groups_of(5).each do |group|
        data = group.compact # remove the nils
        Dynamoid.adapter.batch_write_item(table_name, data)
      end
```

Does that help?

**Comment by NielsKSchjoedt** [comment]
Great I will do, only question I have -> `data` what exactly will that be? `Item` objects or raw hash data or?

**Comment by pboling** [comment]
`data_array` and `data` are arrays of Item objects in your case, yes.

**Comment by welkie** [comment]
Why does Dynamoid limit the number of items that can be batch saved to 25 per request? Was this a limitation of the underlying DynamoDB driver? If not, what was the technical reason for this limitation?

**Comment by pboling** [comment]
This is a limitation of the Amazon DynamoDB service.

> BatchWriteItem
> A single BatchWriteItem operation can contain up to 25 PutItem or DeleteItem requests. The total size of all the items written cannot exceed 16 MB.

Ref: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

**Comment by shawndeprey** [comment]
This is the only thread I found pertaining to actual usage of `batch_write_items` in Dynamoid. I'll leave examples below of how to actually utilize `batch_write_items`. The following is based on a real use-case implemented in a project.
```ruby
# The following examples loads & saves models in batches of 25.
records, batch_size = [], 25
MyModel.batch(batch_size).each do |record| # Batch Read
  record.some_attr = 123 # Updates model, but does not save to database
  records << record
  if records.length >= batch_size
    Dynamoid.adapter.batch_write_item(MyModel.table_name, records.map{|r| r.attributes_for_batch})
    records = []
  end
end
Dynamoid.adapter.batch_write_item(MyModel.table_name, records.map{|r| r.attributes_for_batch}) if records.length > 0
```

Dynamoid Model:
```ruby
# For this example, I built a serializer function on my model which will prepare the model for batch writing. This isn't necessary, but I found it helpful for this type of operation as the `batch_write_item` function does not accept actual Dynamoid models.
class MyModel
  include Dynamoid::Document
  table name: :my_model
  field :some_attr, :integer

  def attributes_for_batch
    {id: self.id, some_attr: self.some_attr}
  end
end
```

**Comment by andrykonchin** [comment]
Great

I would add that there is a more high-level way to create several models at once - `Document.import`:

```ruby
users = User.import([{name: 'Josh'}, {name: 'Nick'}])
```

It involves type casting and could process right values of types, not supported by DynamoDB directly, e.g. `date`/`datetime` or custom serializers.

It's mentioned in the Readme here https://github.com/Dynamoid/dynamoid#object-creation

**Comment by VanPaitin** [comment]
@shawndeprey 
Instead of defining a new `attributes_hash`, can't we just call `.as_json`

**Comment by andrykonchin** [comment]
TBH `to_json` method works well. But only for attribute types that map as is to DynamoDB's native types. Some types that dynamoid supports aren't supported by DynamoDB, e.g. mentioned above Date and DateTime types.

`Dynamoid.adapter.batch_write_item` is a low-level method that does know nothing about dynamoid types. So for any data/time/custom type attribute it should be converted/dumped to the native DynamoDB type. For instance date (by default) is represented as a number of days since 1970 year (similar to Unix time) as a Fixnum. Time is stored (by default) as a Unix time with milliseconds also as a Fixnum. Despite boolean type is supported by DynamoDB natively by default dynamoid stores it as a string 't'/'f' (true/false).
