### ISSUE TITLE
How can I enforce an UpdateItem call with changed  attrs instead of a PutItem?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [Dynamoid/Dynamoid#119]
I use a custom (and predictable) hash_key for my items. 
Dynamodb has the possibility of either updating or creating an object, if you use UpdateItem instead of PutItem (a bit like postgres's `upsert`). 

I would like to utilise this for new items. This way I can avoid a roundtrip checking if the object with the hash_key already exists, before calling save, instead It will just be updated with whatever attributes I send. I cannot find any way to do this though? Is there a way using the existing DSL or would that require me to create the functionality from scratch?

**Comment by pboling** [comment]
I do not know if this is implemented in Dynamo.  I don't, and wouldn't, use it for the use case I have with Dynamoid.  If you can't find any reference to `UpdateItem` in the code, then it isn't implemented, and will require someone with vested interest to do it.

**Comment by andrykonchin** [comment]
`.upsert` method was implemented
