### ISSUE TITLE
Get Item not outputting correct benchmark results

### ISSUE THREAD

**Issue by dahnny012** [Dynamoid/Dynamoid#121]
So I ran  Test.find_by_composite_key(id, range_key)

And this was the result in the log.

(65.0 ms) GET ITEM - [["test_table", "some uuid here", {}]]

It looks like its because the args in https://github.com/Dynamoid/Dynamoid/blob/61165921a2b5a543316d3d70adfd2eda2bcd0bdf/lib/dynamoid/adapter.rb#L148 should be *args?

Not too familiar with ruby.

**Comment by pboling** [comment]
Yes, it looks like it would be cleaner to make it `*args` there.  I will make this change and see what the effect is.
