### ISSUE TITLE
Call For Maintainers!

### ISSUE THREAD

**Issue by pboling** [Dynamoid/Dynamoid#125]
**This project needs more maintainers who use the project more fully.**

**I only use a thin slice of the functionality, as I don't use associations through this gem at all.**

Please step up if you are willing to dig into Amazon DynamoDB docs, and help us with fixing bugs and implementing new features.  I am not an Amazon DynamoDB expert, but I am a Ruby expert.

**Comment by cavi21** [comment]
As @welkie suggest on this other issue **#123** we should keep this conversation going here, and make sense, right?

I mention about reaching out the collaborators on the **[aws-sdk-ruby-record](https://github.com/aws/aws-sdk-ruby-record)** because this gem was created by a [AWS Labs](https://github.com/awslabs) member (@philipmw) so that's why I thought about it.

**Comment by pboling** [comment]
Yes, we should continue discussion here.  Part of the problem with this gem is it does not rely on `aws-sdk-ruby-record` as much as it could, and probably should.  This may be due to timing on the two projects.  @philipmw is no longer involved with this gem, and has passed on maintenance primarily to me, and I use this gem for a very narrow use case, which is working great.

We should evaluate how much we can rebuild on top of `aws-sdk-ruby-record` and leverage things that Amazon is supporting officially.

**Comment by pboling** [comment]
CC @andrykonchin - Are you interested in being a maintainer?  See above discussion.

**Comment by andrykonchin** [comment]
@pboling looks like I am ready :-)

**Comment by welkie** [comment]
@andrykonchin I just wanted to say I still watch this repo even though I don't use AWS (or Rails lol) much these days, but I admire the work you're putting in on this software. I'm sure others feel the same way.

**Comment by pboling** [comment]
@andrykonchin - awesome.  Will see if I can add you.

**Comment by pboling** [comment]
@richardhsu and @andrykonchin are joining myself and @bglusman as the new maintainers of Dynamoid. 👏 

@richardhsu - sorry I didn't ask first if you wanted this role - you have pushed 4 PRs over the last year, and so I assume you use the project.  That being the case the old adage applies - in open source software, if you use it you maintain it.  In the interest of having this project not die it needs active users, and I hardly count, and @bglusman is migrating away from DynamoDB.

If for some reason you don't want the collaborator role, let me know and I'll remove it, no worries.

**Comment by richardhsu** [comment]
@pboling Thanks, and no worries! I do use the project actively and will do my best :)

**Comment by bglusman** [comment]
Yeah we migrated off (from a fairly bad use case/use style) about 8 months ago. I'm still happy to review and help where I can but most of my open source time guess to https://github.com/MasbiaSoupKitchenNetwork/open_pantry these days!
