### ISSUE TITLE
WebMock::NetConnectNotAllowedError in RSpec for application using Dynamoid

### ISSUE THREAD

**Issue by danlelandsuarez** [Dynamoid/Dynamoid#127]
I need to check whether a record has been created in my spec, but running `<TableName>.all.last` in my spec throws a `WebMock::NetConnectNotAllowedError` instead of just retrieving the value. This is how my spec looks:
```
# frozen_string_literal: true
require 'rails_helper'

describe SomeConcern, type: :controller do
  controller(ActionController::Base) do
    include SomeConcern

    def fake_action
      render plain: 'OK'
    end
  end

  before do
    routes.draw do
      get 'fake_action' => 'anonymous#fake_action'
    end
  end

  describe 'my_method_to_test' do
    before :example do
      get :fake_action
    end
    it do
      puts TableName.all.last
    end
  end
end
```

**Comment by pboling** [comment]
DynamoDB is a service, and accessing it results in web requests, unless you have configured your DynamoDB to hit a fake instance somehow.  This is easily done with AWS such that no AWS clients will make any real requests in your test env.

In `spec_helper.rb` (or `rails_helper.rb`):
```
# stub everything
Aws.config[:stub_responses] = true
```

There are a number of other things you could do as well to avoid the requests.

References:
https://aws.amazon.com/blogs/developer/client-response-stubs/
http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html
