### ISSUE TITLE
Question: Persistance

### ISSUE THREAD

**Issue by mgonzaleza** [Dynamoid/Dynamoid#128]
Hi guys, can someone give me hand with this issue I am having?

I am able to save and query my model. However, if I create a new instance of the AWS client with the SDK(say, via the rails console: `dynamoDB = Aws::DynamoDB::Client.new(region: "localhost", access_key_id: "access-key", secret_access_key: "secret-key",endpoint: "http://localhost:9010")`
and try to get the list of tables: `dynamoDB.list_tables` I get an empty response: `#<struct Aws::DynamoDB::Types::ListTablesOutput table_names=[], last_evaluated_table_name=nil>`.

Now, I am able to do: `Zip.all` and get all the records. It is being persisted somewhere, but not sure where since the list_tables method is not showing me my model? Any ideas?

Code below:

# Zip model
class Zip
  include Dynamoid::Document

  table :name => :zip, :key => :zip_id
  field :city, :string
  field :decommisioned, :boolean, {default: false}
  field :location, :string
  field :location_type, :string
  field :region, :string
  field :state, :string
  field :zipcode, :string
  field :zipcode_type, :string
  field :lat, :string
  field :long, :string
end

# Dynamoid Initializer
```
Dynamoid.configure do |config|
    config.adapter = 'aws_sdk_v2' # This adapter establishes a connection to the DynamoDB servers using Amazon's own AWS gem.
    config.namespace = nil # To namespace tables created by Dynamoid from other tables you might have. Set to nil to avoid namespacing.
    config.warn_on_scan = true # Output a warning to the logger when you perform a scan rather than a query on a table.
    config.read_capacity = 5 # Read capacity for your tables
    config.write_capacity = 5 # Write capacity for your tables
    config.access_key = 'access-key'
    config.secret_key = 'secret-key'
    config.endpoint = 'http://localhost:9010' # [Optional]. If provided, it communicates with the DB listening at the endpoint. This is useful for testing with [Amazon Local DB] (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html)
  end
```

**Comment by cignoir** [comment]
It seems that each client points to a different location, but I don't know the clear cause at the moment. 
Could you please try the following method to show tables?
```ruby
p Dynamoid.adapter.list_tables
```

**Comment by mgonzaleza** [comment]
@cignoir That works like a charm, thanks! I wonder, if it's just an issue with DynamoDB Local...

**Comment by pboling** [comment]
@mgonzaleza - 
If you are going to stick around Github please learn how to format code:
Three backticks to start a code block, and three backticks to end a code block:

\`\`\`

**Comment by mgonzaleza** [comment]
@pboling Thanks for the tip and it's all good now.
