### ISSUE TITLE
How can I change the foreign key name??

### ISSUE THREAD

**Issue by devhyunjae** [Dynamoid/Dynamoid#129]
```
class Order
  include Dynamoid::Document
  belongs_to :product, class: :Product

  field :ID
  field :ProductID
end
```

```
class Product
  include Dynamoid::Document
  field :ID
end
```

```
order = Order.find_by_ID('some id')
product = order.product
```

seems like it is using the default fk convention `product_id`

Can I change this like below?

```belongs_to :product, class: :Product, foreign_key: :ProductID```

looks like this doesn't work

**Comment by pboling** [comment]
@andrykonchin do you know if this is possible?

**Comment by andrykonchin** [comment]
@pboling sure it's possible but I cannot estimate required amount of work because I didn't dive into associations mechanism

**Comment by pboling** [comment]
@devhyunjae I do know that if you define a Global Secondary Index you will be able to specify the column name to be queried against.  See my example here if that interests you:
https://github.com/Dynamoid/Dynamoid/issues/168#issuecomment-317951295

**Comment by andrykonchin** [comment]
Implemented in the proposed way. So
```ruby
belongs_to :product, class: :Product, foreign_key: :ProductID
```
should work
