### ISSUE TITLE
Pagination with start row does not work. limit does not work

### ISSUE THREAD

**Issue by gsampathkumar** [Dynamoid/Dynamoid#130]
Using syntax from the below example in the dynamoid documentation. The start row does not get respected and the return results are always from the first row:

address = Address.where(id: <id>).first
Address.eval_limit(5).start(address) # Only 5 addresses.

------------------------------------------------------------------------------------------------
When I try something similar to this:
Address.limit(10_000).batch(100). each { … } 

I get undefined method `limit' for Address:Class\u003e

Updated to the latest version of Dynamoid 1.3.0 and still see this issue.

**Comment by pboling** [comment]
The readme had a typo.  `eval_limit` is the correct syntax, not `limit`.  The readme has been fixed.  Thanks for the report!
