### ISSUE TITLE
Reserved word field problem

### ISSUE THREAD

**Issue by england** [Dynamoid/Dynamoid#133]
Hi, looks like using of reserved words as a field names cause problems like `expected no Exception, got #<NameError: wrong constant name something>` where "something" is a field value.
Test case [here](https://github.com/england/Dynamoid/commit/6a79104f9aea5a694d55e0ebdfd6a7919e0d5bfd)
Any ideas?

**Comment by england** [comment]
Ок, this is a reserved field name for STI

**Comment by pboling** [comment]
There are ways to get around the default field name for STI - but if you can avoid it you really don't want to go down that road.
