### ISSUE TITLE
Range Finding example fix

### ISSUE THREAD

**Issue by archonic** [Dynamoid/Dynamoid#138]
The readme has this as an example:

    User.where("created_at.gt" => DateTime.now - 1.day).all

This caused `ArgumentError: unsupported type, expected Hash, Array, Set, String, Numeric, IO, true, false, or nil, got DateTime` for me. I had to convert to integer instead.

    User.where("created_at.gt" => 1.day.ago.to_i).all

**Comment by archonic** [comment]
Upon inspection, it seems dynamoid can't find anything involving a date range query. Does the date range example work for anyone? I'll have to use the AWS SDK directly if not. Kinda defeats the purpose...

**Comment by pboling** [comment]
That may be due to changes I made in the latest release from a few days ago.  I'll take a look and see if I broke something.

**Comment by mirokuxy** [comment]
still not fixed?

**Comment by pboling** [comment]
There has been no PR to fix this.  I haven't had time to look into it.  I'll see if I can figure something out.

**Comment by richardhsu** [comment]
Can close this issue :) Thanks @andrykonchin, needed this too!

**Comment by pboling** [comment]
@mirokuxy fixed!
