### ISSUE TITLE
default value is shared across instances

### ISSUE THREAD

**Issue by thilo** [Dynamoid/Dynamoid#141]
Hi, while using this extremely helpful gem we came across an issue. As the default value is defined on the class level it was shared between instances that could lead to bugs when the default value was mutated as it would mutate it for all instances using that default. I wrote a test and fix in #140 

I hope that is correct. Let me know if I can improve it any further.

**Comment by pboling** [comment]
Merged, thanks!  I may implement a more robust config solution at some point, but for now this works.
