### ISSUE TITLE
Optimization: Support "COUNT" Queries

### ISSUE THREAD

**Issue by dmitrytrager** [Dynamoid/dynamoid#144]
Version 1.3 introduced [last_evaluated_key support](https://github.com/Dynamoid/Dynamoid/blob/master/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L438) for queries and this is just great. However, when I need to count elements in query result, I will have to go through all items of enumerator which is very slow. For example, with support of "COUNT" queries I could just sum counts from little (1Mb) queries and do not use `items` field from response at all.

Is it worth for optimization?

**Comment by pboling** [comment]
Sounds like it would be worthwhile.  Interested in doing a PR?

**Comment by andrykonchin** [comment]
Implemented
