### ISSUE TITLE
When will you release the next version?

### ISSUE THREAD

**Issue by jnst** [Dynamoid/Dynamoid#175]
I want to use :application_timezone config option.

**Comment by pboling** [comment]
Sometime today. :)  Thanks for the push!

**Comment by andrykonchin** [comment]
I believe the gem should be released ASAP, but...

* I suspect there is a bug with recently added `datetime` type
* not all changes are reflected in Readme
* at least one bug (with limit/batch) isn't fixed and tested

I would like to postpone release for several days to fix these issues

**Comment by pboling** [comment]
@andrykonchin Awesome.  Thanks for keeping track!  I am now a Dynamoid admin, so I can make you a maintainer.

**Comment by andrykonchin** [comment]
New version (1.3.4) is released
