### ISSUE TITLE
Update aws-sdk-resources dependency?

### ISSUE THREAD

**Issue by ijdickinson** [Dynamoid/Dynamoid#209]
The current `gemspec` pins the AWS sdk to version 2.x:

    spec.add_runtime_dependency(%q<aws-sdk-resources>, ["~> 2"])

Increasingly, the gems my project depends on are moving to sdk 3.x, which came out of preview in Aug 2017. So I'm finding this sort of this happening:

    Bundler could not find compatible versions for gem "aws-sdk-core":
    In Gemfile:
    dynamoid (~> 1.3.4) was resolved to 1.3.4, which depends on
      aws-sdk-resources (~> 2) was resolved to 2.0.22, which depends on
        aws-sdk-core (= 2.0.22)

    aws-sdk-rails was resolved to 2.0.1, which depends on
      aws-sdk-ses (~> 1) was resolved to 1.0.0, which depends on
        aws-sdk-core (~> 3)

Any plans to update the dependency in the near-ish future? 

(Yes, I know I could submit a PR, and I'd really like to, but I'm too much up against deadlines at the moment, sorry!)

**Comment by pboling** [comment]
We already have two PRs for this change.  Reviews are welcome.  We are currently determining how and when we will make the switch, so please add your voice to the open PRs.
