### ISSUE TITLE
delete_all method missing

### ISSUE THREAD

**Issue by ijdickinson** [Dynamoid/Dynamoid#210]
In the [README](https://github.com/Dynamoid/Dynamoid#deleting), it says:

> Deleting
> In order to delete some items delete_all method should be used. 
> Any callback wont be called. Items delete in efficient way in batch.
> 
> Address.where(city: "London").delete_all

However, when I tried that it doesn't recognise the `delete_all` method:

    $ RAILS_ENV=test rails c
    Running via Spring preloader in process 5690
    Loading test environment (Rails 5.1.4)
    irb(main):001:0> Incident.where('created_at.lt' => DateTime.now).delete_all
    NoMethodError: undefined method `delete_all' for #<Dynamoid::Criteria::Chain:0x00557e6cb78fc8>
	from (irb):1

Has the API changed?

**Comment by andrykonchin** [comment]
Both `destroy_all` and `delete_all` are available on the master branch.
Only `destroy_all` is available in the current release so just use it.

Some bugs in `destroy_all` were fixed on the master and still aren't released so if you need `destroy_all` - use master.

**Comment by pboling** [comment]
We are preparing a new release with the changes that have landed in master since the last release.  The readme on master branch should always be reflective of the current code in master, and not necessarily the latest released gem.
