### ISSUE TITLE
DynamoId with Boolean type

### ISSUE THREAD

**Issue by vuongvt-rights** [Dynamoid/Dynamoid#214]
Dear DynamoID team.

I saw your developer updated for boolean type of DynamoDB. However, I think you still don't create the Release version.
I am using the newest DynamoId version `dynamoid (1.3.4)` and I can not use `store_as_native_boolean: true` option.
The Pull requests for Boolean type of DynamoDB is [https://github.com/Dynamoid/Dynamoid/pull/213](https://github.com/Dynamoid/Dynamoid/pull/213).

I hope you with create a **new Release version** as soon as possible, because I really need this function.

Thanks and Best Regard.
VuongVT

**Comment by pboling** [comment]
Working on a new release.

**Comment by baloran** [comment]
@pboling He can use the git master version of the gem ? Is not very great for production but working in hotfix ?

**Comment by pboling** [comment]
Discussion on next release is occurring here:
https://github.com/Dynamoid/Dynamoid/pull/215

**Comment by pboling** [comment]
@vuongvt-rights @baloran version 2.0.0 is released.  Please try it out and give feedback!
