### ISSUE TITLE
Conditionals fail while filtering for set type

### ISSUE THREAD

**Issue by pratik60** [Dynamoid/Dynamoid#220]
It appears that the `scan_query` method implemented in `chain.rb` fails with `ArgumentError: value must be enumerable` when using conditions for a set. It works for an array. 

For example: 
```
 model = Class.new do
         include Dynamoid::Document
         table name: :customer
         field :skill_set, :set
       end
model.create(skill_set: Set.new(['ruby']))
model.where('skill_set.contains' => 'ruby').all.to_a # This will fail with the above error
```
I created a little PR with a failing spec here: #219 to ease the process.

**Comment by andrykonchin** [comment]
Fixed. Please check master branch.

**Comment by pratik60** [comment]
Wohooo! Thanks for this :-)
