### ISSUE TITLE
.start (offset) doesn't work?

### ISSUE THREAD

**Issue by mnussbaumer** [Dynamoid/Dynamoid#227]
I tried using `Address.record_limit(n).start(address)`, but with my own models and no matter what is passed to `.start()` the records would always be returned from the same position. FYI I'm using a specific hash key, `email`, and not the default `id` one.

`.record_limit()` & `scan_limit()` seem to be working fine, just that the offset is never applied.

(this using dynamodb local but I imagine it doesn't matter - just pointing it out in case that could change something)

On the other hand, using the same exact local dynamodb instance & table, same credentials, issuing the command directly from from the official sdk works as expected:

```
 client.scan(
          {
            table_name: "thetable_name",
            limit: 2,
            select: "ALL_ATTRIBUTES",
            consistent_read: false,
            exclusive_start_key: {
              "email" => "user_40@email.com", 
            }
          })
```

Will result in 2 records from the first record with that key
Removing `exclusive_start_key` will result in the 2 first records in the table, and so on.

I tried looking at the code but not really sure where the chaining of the methods is happening?
If somebody can point me out to where I could dig it I could work on a PR

ps:
I also noticed that `start` expects a Dynamoid Document? But shouldn't it expect an arbitrary value and then map it to whatever is the defined key in the document?

**Comment by richardhsu** [comment]
What are your configurations for the table? Do you have a global secondary index defined in the model for `email`?

**Comment by mnussbaumer** [comment]
@richardhsu 

So I have got this to work with a few changes - but in fact I don't seem to understand how it even works and passes tests targeting the function.

In `dynamoid/criteria/chain.rb` you can see that:
```
def scan_opts
        opts = {}
        opts[:record_limit] = @record_limit if @record_limit
        opts[:scan_limit] = @scan_limit if @scan_limit
        opts[:batch_size] = @batch_size if @batch_size
        opts[:next_token] = start_key if @start
        opts[:consistent_read] = true if @consistent_read
        opts
  end

Basically it creates a key `next_token`, from the `start_key` method. `start_key` method expects a `dynamoid record` to be passed to it, from which it then calls the `hash_key` method (or `range` depending on table configs)  and then assembles something like this:

`{:next_token=>{:hash_key_element=>"micaelnussbaumer@gmail.com"}}`

So if I call `User.start(a_user_record)`, that's the options that are being sent over and read in `aws_sdk_v2.rb` (the adapter), on the `scan` method, which isn't reading that `next_token` key any way (While most of AWS services use next_token to paginate results, dynamodb doesn't from what I gather). 

My solution is very simple, it's to allow passing a hash instead of a record, it's one line more on `chain.rb`, and then two lines in `aws_sdk_v2.rb`, if a hash is passed into `.start()` it sets one more option as `exclusive_start_key` which gets picked over in the plugin adapter and included in the request. It respects all previous tests, and allows the plugin adapter to still use the `exclusive_start_key` in subsequent queries if `last_evaluated_key` is present and it needs to fetch more records.

I was going to rewrite the `next_token` and change the `start_key` method but it broke 7 tests - although I'm not sure what they're testing since start doesn't work with this simple case.

I can write a small paragraph in the readme and push the changes if this is a PR you would like to merge. It's minimal the changes (3 lines) but they do work and are backwards compatible with whatever.

**Comment by pboling** [comment]
It sounds reasonable.  Would like to get input from others, as I don't have an implementation to test this on right now.

**Comment by richardhsu** [comment]
@mnussbaumer this sounds reasonable, I'm not sure which tests broke originally so cannot speak to what they are testing but please feel free to open a PR and we can review it. But I'm guessing the tests are targeting queries over scans. If this is not the case, we'll need to update the tests suite so please let us know which tests are in question. Finally this does show we're lacking coverage for `scan` in case of a `start`.

Now for the changes, at least for my use cases, I rarely have a `start` without holding onto a particular record since likely due to some kind of scan or querying with pagination. But I can see just having it as a hash of data.

I think that `scan` not utilizing `next_token` is just the fact that the improvement was never made to `scan`. Please make sure in your PR that your update of the code has it pass as `next_token` for consistency when passing the opts to the `scan` in `aws_sdk_adapter` code.

Although the way you describe your solution, we will want to add documentation that if you are passing the hash as the `start` then you need to be sure you are passing a proper `exclusive_start_key` that matches the appropriate composite key for the table or index, otherwise the query/scan will fail. Whereas with record passing, the `chain` module will build the composite key correctly based on the table/index being used.

@mnussbaumer thanks :) Looking forward to the PR!

**Comment by mnussbaumer** [comment]
@richardhsu 
So yes, I agree - I ran into this because I needed to present paginated records, without query (meaning just show them all) but paginated to not put too much strain on the request. After toying a bit more with it I think that the best would be to have a different method of assembling the `start_key` for scans specifically:

Something like this:
```
# ~/lib/dynamoid/criteria/chain.rb
def scan_opts
        opts = {}
        opts[:record_limit] = @record_limit if @record_limit
        opts[:scan_limit] = @scan_limit if @scan_limit
        opts[:batch_size] = @batch_size if @batch_size
        # we removed the :next_token line for this one
        opts[:exclusive_start_key] = scan_start_key if @start
        opts[:consistent_read] = true if @consistent_read
        opts
 end

# we added this method
def scan_start_key
        hash_key = @hash_key || source.hash_key
        range_key = @range_key || source.range_key
        key = {}
        key[hash_key] = @start.send(hash_key) if @start.send(hash_key)
        key[range_key] = @start.send(range_key) if @start.send(range_key)
        key
end

# ~/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb

def scan(table_name, scan_hash = {}, select_opts = {})
        request = { table_name: table_name }
        request[:consistent_read] = true if select_opts.delete(:consistent_read)

        # Deal with various limits and batching
        record_limit = select_opts.delete(:record_limit)
        scan_limit = select_opts.delete(:scan_limit)
        batch_size = select_opts.delete(:batch_size)
        exclusive_start_key = select_opts.delete(:exclusive_start_key)

        request_limit = [record_limit, scan_limit, batch_size].compact.min
        request[:limit] = request_limit if request_limit
        
        # this was added
        request[:exclusive_start_key] = exclusive_start_key if exclusive_start_key

       # ... remaining stuff
end
```

This keeps exactly the same semantics as of now, doesn't introduce any new way of querying. I ran the tests and it doesn't break anything, I would write tests to ensure that it's working, and I double checked with the existing tests and indeed if we start on a scan it will not offset results.

The other way would be as I suggested earlier with the option to pass a hash to the `.start()` method.

So in:
```
# ~/lib/dynamoid/criteria/chain.rb
def scan_opts
        opts = {}
        opts[:record_limit] = @record_limit if @record_limit
        opts[:scan_limit] = @scan_limit if @scan_limit
        opts[:batch_size] = @batch_size if @batch_size
        opts[:exclusive_start_key] = @start if @start && @start.is_a?(Hash)
        opts[:consistent_read] = true if @consistent_read
        opts
 end
```

But in this case it would probably require us to write some warning in case you passed a record to it, since you would expect it to just work if you did so, or add the other method as outlined in the first solution, which then begs the question of why adding this second syntax instead of keeping the same one...

I think the first one is the way to go, if you agree then I'll work on the tests and open a PR

**Comment by mnussbaumer** [comment]
@richardhsu in fact I just noticed that we don't even need to change the aws_sdk_v2.rb plugin file with the first solution as it creates the right fields before passing it to the plugin

**Comment by mnussbaumer** [comment]
@richardhsu It wouldn't break `query` because query will still use the regular `start_key` method and that indeed seems to work when it's querie's case.

Although I just looked into the adapter's `query` method and what it is doing is changing the `next_token` key, into an `exclusive_start_key` one by doing this:

```
opts.delete(:next_token).tap do |token|
          break unless token
          q[:exclusive_start_key] = {
            hk  => token[:hash_key_element],
            rng => token[:range_key_element]
          }
          # For secondary indices the start key must contain the indices composite key
          # but also the table's composite keys
          q[:exclusive_start_key][table.hash_key] = token[:table_hash_key_element] if token[:table_hash_key_element]
          q[:exclusive_start_key][table.range_key] = token[:table_range_key_element] if token[:table_range_key_element]
        end
```
Which seems to just duplicate the logic of the `start_key` method in `chain.rb`. So perhaps the best way is to make `start_key` assemble correctly `exclusive_start_key` from the beginning, and then in both the adapter's `query` and `scan` removed the superfluous translation into this key by just getting it from the opts. 

This would simplify the adapter (as both `scan` & `query` start will only require the `exclusive_start_key` to be there - instead of doing more transformations) and the logic for translating the record passed into `.start()` will be totally on the chain.rb module.

What do you think?

**Comment by mnussbaumer** [comment]
@richardhsu  Perhaps it's just better if I write the PR so you can actually see the changes and test it on your end? I think this last option I mentioned is actually the way to go but if I run into any problem I will write something else

**Comment by richardhsu** [comment]
@mnussbaumer That sounds good and I agree, I like the idea we consolidate it so `chain` builds the correct `exclusive_start_key` and then passes it down and `query` and `scan` just pull it without any extra logic as that'd simplify the logic of the adapter and other places can use it more consistently with how DynamoDB queries are built.

**Comment by andrykonchin** [comment]
Looks like the issue solved here https://github.com/Dynamoid/Dynamoid/pull/229
