### ISSUE TITLE
Table cache will be nil when sidekiq restarting

### ISSUE THREAD

**Issue by ryz310** [Dynamoid/Dynamoid#230]
I use dynamoid on ActiveJob with sidekiq.
But I caught unexpected error when sidekiq worker restarting.

```
gems/dynamoid-2.0.0/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:762:in `describe_table': undefined method `[]' for nil:NilClass (NoMethodError)
    from gems/dynamoid-2.0.0/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:464:in `query'
    from gems/dynamoid-2.0.0/lib/dynamoid/adapter.rb:176:in `query'
    from gems/dynamoid-2.0.0/lib/dynamoid/criteria/chain.rb:150:in `block in records_via_query'
    from gems/dynamoid-2.0.0/lib/dynamoid/criteria/chain.rb:130:in `each'
    from gems/dynamoid-2.0.0/lib/dynamoid/criteria/chain.rb:130:in `each'
    from gems/dynamoid-2.0.0/lib/dynamoid/criteria/chain.rb:130:in `each'
```

It seems that `#describe_table` method was called before `#connect!` method calling or `adapter.respond_to?(:connect!)` had return `false`.
What happen to the dynamoid when the sidekiq restarting?
I need anyone help. Thank you.

https://github.com/Dynamoid/Dynamoid/blob/56429229147b9a2e03481ca9b88b8d8ea7a7344c/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L761-L765

https://github.com/Dynamoid/Dynamoid/blob/56429229147b9a2e03481ca9b88b8d8ea7a7344c/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L55-L58

https://github.com/Dynamoid/Dynamoid/blob/56429229147b9a2e03481ca9b88b8d8ea7a7344c/lib/dynamoid/adapter.rb#L28-L36

My environments are following.

- dynamoid 2.0.0
- ruby 2.4.3
- rails 5.1.0
- sidekiq 5.0.5

**Comment by andrykonchin** [comment]
Are you able to reproduce the issue?

Could you try to reproduce it on this branch? https://github.com/Dynamoid/Dynamoid/tree/fix-describe-table-issue-230

**Comment by ryz310** [comment]
Thank you for your response! Let me see.

**Comment by ryz310** [comment]
I tried reproduces the error many times but I couldn't. 
I will report again if it reproduces and I can provide more information.
Thank you for your quick response.

**Comment by pboling** [comment]
Thanks.  Will reopen if you report back with a recurrence.

**Comment by pboling** [comment]
@andrykonchin we should open a PR for that branch?

**Comment by andrykonchin** [comment]
@pboling I think no. It's not a fix, just removing some legacy logic. I will add it to the first my PR

**Comment by ryz310** [comment]
I report that I've occurred same exception again with dyanmoid v3.2.0.
I'm using jenkins on deploy, but when it's failure starting sidekiq with some condition, the value of `table_cache` sometimes will be `nil` not `{}`. It was probably the similar situation as before.

It's quite rare case so I think no need fix it, just a reporting.

```
gems/dynamoid-3.2.0/lib/dynamoid/adapter_plugin/aws_sdk_v3.rb:603:in `describe_table': undefined method `[]' for nil:NilClass (NoMethodError)
    from gems/dynamoid-3.2.0/lib/dynamoid/adapter_plugin/aws_sdk_v3.rb:491:in `block in query'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:194:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:194:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:194:in `block in pages_via_query'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
    from gems/dynamoid-3.2.0/lib/dynamoid/criteria/chain.rb:155:in `each'
```

https://github.com/Dynamoid/dynamoid/blob/a64b8e155c0fe44b5998f0004caccf2266e10c54/lib/dynamoid/adapter_plugin/aws_sdk_v3.rb#L602-L606

**Comment by andrykonchin** [comment]
The issue should be fixed in https://github.com/Dynamoid/dynamoid/pull/373
