### ISSUE TITLE
Outdated documentation on rubydoc.info

### ISSUE THREAD

**Issue by andrykonchin** [Dynamoid/Dynamoid#233]
There is a link to generated documentation in the Readme - http://rdoc.info/github/Dynamoid/Dynamoid/frames.

We need either to keep it up to date or to remove it at all.

**Comment by pboling** [comment]
I have updated it.  I just went to add a project to the site in the top right corner, and re-added it.  That causes it to re-pull, and update.  👍   We should keep it up to date, I use rdoc.info very frequently to reference gem documentation.

**Comment by andrykonchin** [comment]
I have set up Github hook to update rubydoc.info automatically

https://rubydoc.tenderapp.com/kb/git-integration/adding-a-rubydocinfo-post-receive-commit-hook-on-github

**Comment by pboling** [comment]
Very nice!
