### ISSUE TITLE
Strange behavior for rake dynamoid:create_tables

### ISSUE THREAD

**Issue by baloran** [Dynamoid/Dynamoid#237]
I was using `rake dynamoid:create_tables` to launch tests. But an error occured on require of the model.
```ruby
  task :create_tables => :environment do
    # Load models so Dynamoid will be able to discover tables expected.
    Dir[ File.join(Dynamoid::Config.models_dir, "*.rb") ].sort.each { |file| require "./#{file}" }
    if Dynamoid.included_models.any?
      tables = Dynamoid::Tasks::Database.create_tables
      result = tables[:created].map{ |c| "#{c} created" } + tables[:existing].map{ |e| "#{e} already exists" }
      result.sort.each{ |r| puts r }
    else
      puts "Dynamoid models are not loaded, or you have no Dynamoid models."
    end
  end
```

I have changed `require file` to `require "./#{file}"`, and it's working. Ugly, no ?

I have seen this "solution" here: https://stackoverflow.com/a/41991909/2707937

I don't know if is my configuration ? I don't know how to test this.

xoxo

**Comment by andrykonchin** [comment]
I think the correct solution is to change `Dynamoid::Config.models_dir` from default `app/models` to `./app/models`

**Comment by baloran** [comment]
Ok. I made the change !

**Comment by baloran** [comment]
PR made.

**Comment by baloran** [comment]
Ok, I doesn't understant.. sorry @andrykonchin for this pr, I closed.

**Comment by pboling** [comment]
I think the way you have done it, `require "./#{file}"`, despite being ugly, is the correct solution for this use case. 👍

**Comment by baloran** [comment]
I have just changed the models_dir with `./app/models` 🙃
