### ISSUE TITLE
Cannot find nor destroy items. The provided key element does not match the schema

### ISSUE THREAD

**Issue by elisoncampos** [Dynamoid/Dynamoid#240]
Hi, Im not sure this is a bug within dynamoid since the table was manually created direct on DynamoDB  so I'm more asking for support. Given the following model:

```ruby
class Domain
  include Dynamoid::Document

  table name: (Rails.env.production? ? 'router' : 'router-stg')

  field :domain
  field :is_alboom_domain, :boolean, store_as_native_boolean: true
  field :path
  field :service
  field :user_id, :integer
end
```
**NOTE**: router was the table created directly from aws dynamodb admin page, router-stg is generated by running `rails dynamoid:create_tables` on development and staging. When I run my code against dynamodbLocal (https://hub.docker.com/r/deangiberson/aws-dynamodb-local/) the code works as expected.

When I try to run find (Domain.find, Domain.where works fine) and destroy on a resource. I get the following exception:

```ruby
Aws::DynamoDB::Errors::ValidationException: The provided key element does not match the schema
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:112:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/seahorse/client/request.rb:70:in `send_request'
	from /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.10.103/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:370:in `get_item'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/adapter.rb:148:in `block (3 levels) in <class:Adapter>'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/adapter.rb:53:in `benchmark'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/adapter.rb:148:in `block (2 levels) in <class:Adapter>'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/adapter.rb:91:in `read'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/finders.rb:80:in `find_by_id'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/identity_map.rb:31:in `find_by_id'
	from /app/vendor/bundle/ruby/2.3.0/gems/dynamoid-2.0.0/lib/dynamoid/finders.rb:38:in `find'
	from (irb):2
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Im using Rails 5.1.5 with aws-sdk 2 and dynamoid 2. Any help appreciated.

**Comment by andrykonchin** [comment]
Looks like either partition key name or its type differs in production. Have you checked and compare them with partition key of staging table?

**Comment by elisoncampos** [comment]
I did check these things and what i found is that our production table has a primary key and a sort key. Is that the reason im having these issues? Is that something I can set up my model to address? I couldn't find anything in the documentations about sort keys.

**Comment by andrykonchin** [comment]
Yes, it may be a cause of the issue as far as you MUST specify both partition and sort key to load particular item (if sort key is declared).

Sort key is also known as range key (it is an old name) and this name is still used in Dynamoid.

`Document.find(pk, range_key: 'some-sort-key')`

To declare range key in model you need to use following DSL:

```ruby
class Document
  ...
  range :posted_at, :datetime
end
```

**Comment by andrykonchin** [comment]
@pboling Looks like there is nothing about range key in the readme.

It's also confusing to use old terms like `hash key` and `range key` as far as new terms `partition key` and `sort key` are used in DynamoDB documentation. I propose to use only new terms in source code. I would like to get rid of old terms in existing code base and in public interface what is a breaking change. 

Does it make sense?

**Comment by elisoncampos** [comment]
Hey, thanks. It was exactly that. I didn't know range and hash keys were old terms so the documentation was right all along.  I'm closing this issue since it's not really an issue and I found my answer. Thanks again.

**Comment by pboling** [comment]
@andrykonchin breaking changes are fine, so long as we version the release properly.  There may also be a way to soft deprecate the old names before removing them entirely.
