### ISSUE TITLE
where.not or ne Operator

### ISSUE THREAD

**Issue by yoonwaiyan** [Dynamoid/Dynamoid#241]
I'm still new to this repo. I've tried to search through the source code and seems like there's no available query similar to `.where.not` in Rails. In AWS DynamoDB console table filters the not equal is available and I checked it's available in the AWS documentation too. Can we have this feature in Dynamoid so that I can make the backend switch from ActiveRecord simpler?

**Comment by pboling** [comment]
You are correct that we haven't formalized a shorthand chained method for the `ne` operator.  @andrykonchin I'm thinking it may no be too hard, but also there may be some unexpected behaviors with chaining multiple conditions, AND vs. OR?  I haven't really used the chaining scoping aspect of the gem yet.

**Comment by andrykonchin** [comment]
@pboling It isn't hard to add `not` chain method except I don't see any way to negate `in` operator. So e.g.
```ruby
Document.where.not('version.in' => [1, 2, 3])
```

will not work. May be I missed something in documentation (https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html).

New condition syntax allows more complex expressions (https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html) but we still use deprecated one.

Actually even `ne` operator isn't implemented in `where` conditions. So at least we can add it.

**Comment by pboling** [comment]
OK, let's start with adding support for `ne` operator.  Perhaps after that our goal should be to move to the supported condition syntax?  And *then* add a chained `not`?

**Comment by andrykonchin** [comment]
@pboling Yep, definitely. It will improve querying drastically and make it more SQLish

I think it's right time to consider new minor release. There are two issues I would like to complete before it - this one with `ne` operator and handling not processed items in batch operations.

Does it make sense?

**Comment by pboling** [comment]
Yes!  Looking forward to seeing what you do.  Sorry I don't have more time to help.  I am up to my ears in projects.
