### ISSUE TITLE
Not working with aws-sdk-core 3.0

### ISSUE THREAD

**Issue by sandeepnagra** [Dynamoid/Dynamoid#247]
We need to install both aws-sdk-dynamodb and aws-sdk-s3 where s3 particulary requires aws-sdk-core version  to be ~> 3.0 however dynamoid v2 requires the aws-sdkcore to be ~> 2

Also, if we just do `gem install dynamoid` it install an old version ~0.7. You should update the default version to either the most recent or most stable.

**Comment by sandeepnagra** [comment]
gem install dynamoid installs ver 0.7 which doesn't have any conflict however that version is not even listed here - https://rubygems.org/gems/dynamoid

**Comment by pboling** [comment]
1. There are a lot of changes on the master branch that are unreleased.
2. The next release should be soon, perhaps within the next month or so.
3. The next release will *still* be on `aws-sdk-core` v2.
4. There are open PRs to upgrade Dynamoid to `aws-sdk-core` v3, but none of them are complete.  If you would like to help us with testing, or work on any open issues to move us toward a release faster, it is appreciated.
5. The release _after_ the next release, will be a major release version upgrade, and will include breaking changes, with `aws-sdk-core` v3 compatibility.

**Comment by andrykonchin** [comment]
Done https://github.com/Dynamoid/Dynamoid/pull/267
