### ISSUE TITLE
Undefined method index

### ISSUE THREAD

**Issue by pawneetdev** [Dynamoid/Dynamoid#248]
When I use the following code, I get **"method_missing': undefined method `index' for Test"** error

```
class Test < ActiveRecord::Base

	include Dynamoid::Document

	table :name => :tests, :key => :id, :read_capacity => 20, :write_capacity => 20

	field :source
	field :data
	field :entity_id, :string
	field :entity_type
	field :processed, store_as_native_boolean: true

	validates_presence_of :source
	validates_presence_of :entity_id
	validates_presence_of :entity_type

	index :entity_id

end

```

I tried both the variant mentioned in the documentation:

```
index :entity_id
index [:entity_id]
```

**Comment by andrykonchin** [comment]
Could you please provide a simple test to reproduce the issue?

**Comment by pboling** [comment]
@pawneetdev `class Test < ActiveRecord::Base` is a misreading of the documentation.  This gem does not enhance ActiveRecord models.  It replaces ActiveRecord as the ORM for a data model.  You can still use ActiveRecord for *other* classes, but if you want to use Dynamoid to back a specific class it will *not* be an ActiveRecord class.

**Comment by pawneetdev** [comment]
My bad. Sorry and thank I was able to fix it

**Comment by pawneetdev** [comment]
@andrykonchin I am getting this when I query the model in the console

![image](https://user-images.githubusercontent.com/12933022/37698751-4a0e4ece-2d0a-11e8-8fc1-8f5f4808c6e4.png)

**Comment by andrykonchin** [comment]
I see. Thanks. Will fix the warning text.
