### ISSUE TITLE
Entry with datetime

### ISSUE THREAD

**Issue by arkes** [Dynamoid/Dynamoid#251]
Hey,

I'm having several entries that I'm unable to delete.
When I'm fetching this entry and reload it, it come back with `Dynamoid::Errors::RecordNotFound: Couldn't find MyModel with 'id'=8fbfc5ee-...`. I'm using an index with a  datetime range.
It seems that the method `dump_field` and `undump_field` are using 2 different time class. `dump_field` use `Time` and `undump_field` use `DateTime`

I'm using 
ruby: `ruby 2.3.3p222`
gem: `dynamoid (2.0.0)`
I tried with other versions of Ruby and Rails.

```
> 10.times { x = Time.current; puts "#{x.to_f} - #{x.to_datetime.to_f} - #{x.to_f == x.to_datetime.to_f}" }
1522135554.9757178 - 1522135554.975718 - false
1522135554.975918 - 1522135554.975918 - true
1522135554.975996 - 1522135554.975996 - true
1522135554.9760509 - 1522135554.976051 - false
1522135554.976595 - 1522135554.976595 - true
1522135554.9766479 - 1522135554.976648 - false
1522135554.9766998 - 1522135554.9767 - false
1522135554.976751 - 1522135554.976751 - true
1522135554.9768 - 1522135554.9768 - true
1522135554.9768488 - 1522135554.976849 - false

> 10.times { x = DateTime.current; puts "#{x.to_f} - #{x.to_time.to_f} - #{x.to_f == x.to_time.to_f}" }
1522135556.917298 - 1522135556.9172978 - false
1522135556.917488 - 1522135556.917488 - true
1522135556.9176 - 1522135556.9176 - true
1522135556.9177 - 1522135556.9177 - true
1522135556.917799 - 1522135556.917799 - true
1522135556.917896 - 1522135556.917896 - true
1522135556.917992 - 1522135556.9179919 - false
1522135556.91809 - 1522135556.9180899 - false
1522135556.919354 - 1522135556.9193542 - false
1522135556.919487 - 1522135556.919487 - true
```

I think the solution should be to just to use the same time class inside `dump_field` and `undump_field`. This issue is still present on master.
I'm happy to create a PR if you want to.

**Comment by arkes** [comment]
I made all the changes to use only `Time`, but the issue is still there (with less occurrences). 
This issue affect reload and destroy and probably update.
After looking deeply into the code the problem is for a date object or a time object the field follow this flow `Fetch -> float to time -> time to float -> reload` which in some case the float rounding is not the same, which end up with `Dynamoid::Errors::RecordNotFound: Couldn't find MyModel with 'id'=8fbfc5ee-...`
A fix for this issue would be to keep the original fields value and only change them if one the fields are modified. In this case there will be no transformation or rounding issue.

**Comment by andrykonchin** [comment]
I tried to reproduce the issue with `Time` and failed (for 2.2, 2.3 and 2.4 versions). Looks like it should work:

```ruby
(1 .. 10000).map { t = Time.now; t.to_f == Time.at(t.to_f).to_f }.all?
=> true
```

**Comment by andrykonchin** [comment]
Working on the fix.

If you need a temporary workaround you can store time in the ISO-8601 string format with `store_as_string` field option

```ruby
   field :sent_at, :datetime, store_as_string: true
```

**Comment by andrykonchin** [comment]
Fixed

@arkes Could you please check if the fix solves the issue in your case?
