### ISSUE TITLE
New vs Create inside dynamoid

### ISSUE THREAD

**Issue by baloran** [Dynamoid/Dynamoid#258]
Hey

After trying to use `Document.new` to try to validate before save the document, I noticed that it's put item. But the behavior of .new it's to create object but not save it ? I don't know if I make mistake.

xoxo

```ruby
Document.new(
  name: "Baloran",
  kind: "customer"
)
```

**Comment by pboling** [comment]
@andrykonchin @richardhsu does this make sense to you?

**Comment by richardhsu** [comment]
@baloran can you provide more details, more code snippets or logs, I cannot reproduce this and do not see any reason a `put` call would be made before a `save` is called.

**Comment by pboling** [comment]
@baloran My guess is that you have some side-effect in your code that is causing the Document to be saved when you aren't expecting it.

I do not think this is related to Dynamoid at all.  Will leave this issue open for a few more days to give you time to respond, but I don't see any way this could be a bug in Dynamoid.
