### ISSUE TITLE
Concurrent insert with dynamic table, not works!

### ISSUE THREAD

**Issue by mauriciovalencia** [Dynamoid/Dynamoid#259]
Class LogData

	include Dynamoid::Document

	field :id_user, :integer
	field :array_data, :array

    def self.property_shown_as_marker_cumulative(session_data, additional_data)
        additional_data[:key_name] = 'table_1'
        insertlog(session_data,additional_data)
        additional_data[:key_name] = 'table_2'
        insertlog(session_data,additional_data)
        additional_data[:key_name] = 'table_3'
        insertlog(session_data,additional_data)
    end

    private

    def self.insertlog(session_data, additional_data)
        table :name => :"#{additional_data[:key_name]}", :key => :id, :read_capacity => 400, :write_capacity => 400      
        if(session_data[:user_id] != nil)
          self.create(
              id_user: session_data[:user_id],
              array_data: session_data[:array_ids]
          )          
        end
    end

end

Console log
(267.91 ms) PUT ITEM - ["dynamoid__development_table_1",.....
(82.56 ms) PUT ITEM - ["dynamoid__development_table_1",......
(95.37 ms) PUT ITEM - ["dynamoid__development_table_1",......

Why didn´t works fine?, where is the error?, why is not inserting on table_1, table_2, table_3 table, if not on table_1 persistently?

Dynamoid 2.2.0
Ruby 2.1.2
Rails 4.2.0

Regards.

**Comment by pboling** [comment]
I believe we intend to support a single table per class currently.  I am not aware of a way around this.  @richardhsu @andrykonchin have you ever needed to do something like this?

**Comment by mauriciovalencia** [comment]
Well, I did it with Mongoid very easily, therefore I think that in Dynamoid could be possible too without creating unnecessary classes, I come from the world nodejs and things like that are easily possible.

**Comment by richardhsu** [comment]
I have not needed it and I believe right now we have it mapped 1 class per table just as ActiveRecord codes. 

This doesn't seem to follow paradigms I'm used to in Rails though so not sure if we'd necessarily want to do this?

Is there a particular larger use case for wanting to change the table so we could potentially implement something generalized? @mauriciovalencia

**Comment by pboling** [comment]
Dynamoid is an ORM, which "Maps" a "Relation" from a ruby "Object" (class) to a resource (table) in the datastore.  If you don't want to use it like an ORM then perhaps you should use another DynamoDB ruby client.

The idea in this project is that you create a ruby class per table.  You can use class inheritance, or module composition, to not duplicate everything and share code, while also declaring the table once per individual class.

**Comment by mauriciovalencia** [comment]
Thanks a lot, with aws gem was more code to build, but!, works fine!, regards!
Issue closed for me!
