### ISSUE TITLE
update_attributes for nested attributes

### ISSUE THREAD

**Issue by Elyahou** [Dynamoid/Dynamoid#262]
I see that it is possible to updade nested attributes using dots like explained  [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Attributes.html#Expressions.Attributes.NestedAttributes)

Do Dynamoid support this ?

**Comment by andrykonchin** [comment]
Sorry for the delay.
I guess - no. Neither Dynamoid nor DynamoDB itself.

**Comment by pboling** [comment]
@andrykonchin You may have missed the link in OP:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Attributes.html#Expressions.Attributes.NestedAttributes

I think it is supported by DynamoDB, but I am not sure how that would be handled by Dynamoid.
