### ISSUE TITLE
Manage global secondary index

### ISSUE THREAD

**Issue by vitalinfo** [Dynamoid/Dynamoid#263]
Does it possible to add new global_secondary_index to existed table?
Thanks

**Comment by andrykonchin** [comment]
`Dynamoid` doesn't support migrations like creating/removing indices or changing table capacity now. But surely it can be done with AWS Ruby SDK's [update_table](https://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html#update_table-instance_method) method
