### ISSUE TITLE
Dynamoid does not fail correctly if it cannot connect to an endpoint

### ISSUE THREAD

**Issue by iblue** [Dynamoid/Dynamoid#27]
Given the configured endpoint is not reachable:

Because of an unconditional rescue in `concurrent-ruby-0.9.2/lib/concurrent/atom.rb`, line 97 the `ECONNREFUSED` exception created in `dynamoid-1.0.0/lib/dynamoid/adapter.rb`, line 20 is catched and ignored.

Therefore, when I cannot connect to an endpoint, I get an `undefined method`include?' for nil:NilClass`

To reproduce, just try to save any object with an endpoint of "localhost:3000" without DynamoDB running.

I am not sure if this should be fixed in concurrent-ruby or here. Maybe it would be a good idea, to query the tables first, then swap it in.

**Comment by mstahl** [comment]
I am also experiencing this error but in a slightly more bizarre circumstance. When I have my Rails app and DynamoDB local running in a docker-compose cluster, everything works great. I'm able to save and query for objects in DynamoDB just fine. When I run the Rails app in Docker but run DynamoDB in a separate VM or locally on my laptop, _*even though I am able to telnet to the right port on the host machine from Docker*_, I get this error. I also get it if DynamoDB local isn't running.

The swallowing of exceptions most definitely needs to get fixed on the concurrent-ruby side of things, but I suspect something else might be going on here. It takes nearly 5 minutes to time out, too, so this has been really hard to figure out.

This issue has been open for over a month now. Is anyone actively developing Dynamoid still?

**Comment by pboling** [comment]
Yes, new maintainers just came on board.  We are working through the issues now.

**Comment by andrykonchin** [comment]
Currently I reproduce meaningful `Seahorse::Client::NetworkingError` exception.
Maybe we need to wrap it into `Dynamoid`'s one like `Dynamoid::Errors::NetworkError`

```
.../ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to localhost:3000 (Connection refused - connect(2) for "localhost" port 3000) (Seahorse::Client::NetworkingError)
```

Script to reproduce

```ruby
require 'aws-sdk'
require 'dynamoid'

Aws.config.update({
  region: 'us-west-2',
  credentials: Aws::Credentials.new('REPLACE_WITH_ACCESS_KEY_ID', 'REPLACE_WITH_SECRET_ACCESS_KEY'),
})

Dynamoid.configure do |config|
  config.endpoint = 'http://localhost:3000'
end

class Document
  include Dynamoid::Document
end

Document.create_table
```

**Comment by pboling** [comment]
I think we should allow the underlying transport errors to bubble up. 👍
