### ISSUE TITLE
custom type validation with array

### ISSUE THREAD

**Issue by NatasG** [Dynamoid/dynamoid#272]
I have a model like this:

```

class A
  include Dynamoid::Document
  table name: :a
  field :b, B
  field :c, Array[C]

```

I define the custom type `B` and `C`, they do validations for themselves.
But in this way, when I parse data from a json, it throws an exception: *#<ArgumentError: Unknown type [C]>*

To fix this exception, I change my model to this:

```
class A
  include Dynamoid::Document
  table name: :a
  field :b, B
  field :c, :array

```
There is no exception now. But I couldn't get my custom type `C`. 
So I couldn't validate my field c.

Can you help me?

**Comment by andrykonchin** [comment]
I guess you need to have custom type ArrayOfC which implements required interface ( `dynamoid_load` and `dynamoid_dump` methods)

As declared in [Readme](https://github.com/Dynamoid/Dynamoid#fields) field can be only:
* scalar type like string, integer or boolean
* collection of scalar values like array and hash or nested collection
* or custom type

If field is collection (array in your example) it can contain elements of any scalar/collection type but shouldn't contain elements of custom type.

If you think it's a common case to have collection/array of the same custom type - please create appropriate issue. Dynamoid already [supports set of integer](https://github.com/Dynamoid/Dynamoid#note-on-set-type)

**Comment by NatasG** [comment]
What do you mean `ArrayOfC`, example?

**Comment by NatasG** [comment]
Thank you.
I think it is necessary to support custom type in collection.

**Comment by pboling** [comment]
I think for now the code example given by @andrykonchin is how we will support collections with custom types.  We can add that example to a wiki for documentation of the current support for custom collections.

**Comment by pboling** [comment]
Actually going to leave this open until we get the example added to documentation.

**Comment by andrykonchin** [comment]
Done
