### ISSUE TITLE
Dynamoid destroy does not check lock_version

### ISSUE THREAD

**Issue by sumocoder** [Dynamoid/Dynamoid#28]
I am interested in knowing if this was a design decision or is it a bug. I would assume that you shouldn't be able to delete a record if it is out of date.

**Comment by philipmw** [comment]
Thanks for the report. I believe it's a bug. DynamoDB's SDK checks version number when deleting.

[SDK](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaVersionSupportHLAPI.html):
> The DynamoDBMapper assigns a version number when you first save the object, and it automatically increments the version number each time you update the item. Your update or delete requests will succeed only if the client-side object version matches the corresponding version number of the item in the DynamoDB table.

**Comment by sumocoder** [comment]
Thank you for the update. I have a fix for this if you would like to have a look.

**Comment by philipmw** [comment]
I'd love it. Submit a PR?

**Comment by sumocoder** [comment]
Submitted, please review and comment.

**Comment by philipmw** [comment]
Merged as #29. Thanks for the contribution.
