### ISSUE TITLE
cant save hash using raw column type if the hash has integers for the keys

### ISSUE THREAD

**Issue by varchar** [Dynamoid/dynamoid#296]
Any hash being saved into a "raw" column breaks if the hash uses integers for keys

```class ProductFitList
  include Dynamoid::Document

  table key: :customer_id
  field :product_ids_with_score, :raw
```

# /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/seahorse/model/shapes.rb:198:in `member?'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:46:in `block in structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `each_pair'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:77:in `member'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:47:in `block in structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `each_pair'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:77:in `member'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:68:in `block in map'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:67:in `each'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:67:in `with_object'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:67:in `map'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:79:in `member'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:47:in `block in structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `each_pair'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:44:in `structure'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/param_converter.rb:28:in `convert'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/aws-sdk-core/plugins/param_converter.rb:19:in `call'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/seahorse/client/plugins/response_target.rb:21:in `call'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/seahorse/client/request.rb:70:in `send_request'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/aws-sdk-core-2.11.8/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/dynamoid-2.2.0/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:452:in `update_item'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/dynamoid-2.2.0/lib/dynamoid/adapter.rb:160:in `block in method_missing'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/dynamoid-2.2.0/lib/dynamoid/adapter.rb:53:in `benchmark'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/dynamoid-2.2.0/lib/dynamoid/adapter.rb:160:in `method_missing'
     # /Users/charlie/.rvm/gems/ruby-2.3.5@letote/gems/dynamoid-2.2.0/lib/dynamoid/document.rb:183:in `upsert'
     # ./app/models/product_fit_list.rb:33:in `save_product_fit_list'

**Comment by andrykonchin** [comment]
Could you please provide full complete example to reproduce the issue?

**Comment by varchar** [comment]
pfl = ProductFitList
pfl.product_ids_with_score = {1 => 100}
pfl.save

this creates the above stacktrace.  What else are you lookng for?

**Comment by andrykonchin** [comment]
OK. Got it. Thanks.

**Comment by varchar** [comment]
Another question, is using "raw" vs "serialized" faster?  using a type of "serialized" allows a integer hash key to work

**Comment by andrykonchin** [comment]
There may be a very small difference.

Attributes are sent to DynamoDB as a JSON document. `raw` attribute is converted to JSON directly. `serialized` field is converted to YAML and then is put as a string in a result JSON document.

So the question is - what serialization is faster - JSON or YAML.

**Comment by andrykonchin** [comment]
Fixed
