### ISSUE TITLE
Dynamoid doesn't seem to use query option `:count` for `.count` method.

### ISSUE THREAD

**Issue by mmhan** [Dynamoid/dynamoid#301]
I don't see anything in the README but it seems to me like calling something like `Document.where(published: true).count` is still either querying/scanning without aws-sdk's `:count` [option](https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/DynamoDB/Client.html#query-instance_method).

**Comment by andrykonchin** [comment]
Yep. You are correct.

There is an issue already https://github.com/Dynamoid/dynamoid/issues/144

**Comment by mmhan** [comment]
Oh.. cool. Looks like it's still in help wanted stage. I'll see what I can do.

**Comment by andrykonchin** [comment]
TBH It requires either massive copy-paste or massive refactoring. That's why I postponed it so long. Hope it will be part of the next minor release.

**Comment by pboling** [comment]
Closing in favor of #144.  Renamed #144 to make it clear.
