### ISSUE TITLE
How can I create table attributes with custom field names?

### ISSUE THREAD

**Issue by myweddingwala** [Dynamoid/dynamoid#336]
I have a table defined with attributes GSI-1, and GSI-2 and so on, and since the attribute name contains "-", I am not able to use Dynamoid, is there any way I can define custom attribute names?

**Comment by andrykonchin** [comment]
Not sure if I understood you correctly.

You can't definitely call generated getters/setters for these attributes, as far as `GSI-1` isn't a valid method name in Ruby.

But you have access to the model attributes with `attributes` method:

```ruby
class Post
  include Dynamoid::Document
  
  field :'foo-bar'

  def foo_bar
    attributes[:'foo-bar']
  end

  def foo_bar=(str)
    attributes[:'foo-bar'] = str
  end
end
```

**Comment by andrykonchin** [comment]
Since it’s been six months, I hope things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed
