### ISSUE TITLE
No connection pool with 'primary' found

### ISSUE THREAD

**Issue by ralberth** [Dynamoid/dynamoid#361]
I'm seeing the following error when I run my rspec tests from a rake build:

```
...
 12) ErrorsController should log a FATAL if a redirect from within 404s
      Failure/Error: raise ConnectionNotEstablished, "No connection pool with '#{spec_name}' found." unless pool

      ActiveRecord::ConnectionNotEstablished:
        No connection pool with 'primary' found.
      # .../activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1007:in `retrieve_connection'
      # .../activerecord-5.2.0/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
      # .../activerecord-5.2.0/lib/active_record/connection_handling.rb:90:in `connection'
      # .../activerecord-5.2.0/lib/active_record/fixtures.rb:536:in `create_fixtures'
      # .../activerecord-5.2.0/lib/active_record/fixtures.rb:1031:in `load_fixtures'
      # .../activerecord-5.2.0/lib/active_record/fixtures.rb:1002:in `setup_fixtures'
      # .../activerecord-5.2.0/lib/active_record/fixtures.rb:860:in `before_setup'
      # .../rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:126:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
      # .../rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
      # .../rspec-core-3.7.0/lib/rspec/core/example.rb:447:in `instance_exec'
      # .../rspec-core-3.7.0/lib/rspec/core/hooks.rb:375:in `execute_with'
...
```

Dynamoid worked prior to upgrading from Rails 5.0 to rails 5.2, which might be the culprit.

My (single) model object:

```ruby
require 'dynamoid'

class Coffeebrand
  include Dynamoid::Document

  table key: :brandname
  field :rating
end
```

My initializer that sets up Dynamoid:

```ruby
require 'dynamoid'

Aws.config.update region: 'us-east-1'

Dynamoid.configure do |config|
  config.region = 'us-east-1'
  config.namespace = nil
  config.warn_on_scan = false
  config.timestamps = false
  config.logger.level = :debug
  # config.endpoint = 'http://localhost:3000' # for testing with Amazon Local DB
end
```

I don't have a `config/database.yml` because I don't connect to any SQL-based databases.
I tried connecting to various databases, but still see the same error above.

It looks like rspec setup for fixtures is trying to connect to a database maybe...?

**Comment by andrykonchin** [comment]
Looks like this issue isn't connected to Dynamoid.

> It looks like rspec setup for fixtures is trying to connect to a database maybe...?

I think you are right. If you don't use ActiveRecord and don't set up connection with `config/database.yml`/`DATABASE_URL` env variable ActiveRecord shouldn't be required at all. Maybe this [post](https://revelry.co/rails-app-without-database/) can help.

Does it make sense?

**Comment by andrykonchin** [comment]
Since it’s been five months, I hope things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.
