### ISSUE TITLE
Problem saving object to DynamoDB

### ISSUE THREAD

**Issue by fabiensebban** [Dynamoid/dynamoid#366]
I tried to create rails 6 (ruby version: 2.6.3) project using Dynamoid to store data in my DynamoDB database.

To make sure my data is saved correctly in dynamoDB, I followed the configuration step mentioned in the README file (https://github.com/Dynamoid/dynamoid). I create a user model as following:

```
class User
  include Dynamoid::Document

  field :name
end
```

After configuration, I tried to save a user using the rails console.

As a result, I have this error :

```
2.6.3 :012 > u = User.create(name: 'John')
Traceback (most recent call last):
        1: from (irb):12
NoMethodError (undefined method `force_change' for #<ActiveModel::NullMutationTracker:0x00007faf8e24bef0>)
```

Anybody had the same issue? Dimanoid is supported by rails 6?

**Comment by andrykonchin** [comment]
Nice catch.

Dynamoid doesn't support Rails 6. Despite Rails 6 isn't released yet it would be great have it supported  beforehand.

Will work on it ASAP and it will be released in the next Dynamoid minor release.

**Comment by andrykonchin** [comment]
Fixed in https://github.com/Dynamoid/dynamoid/pull/368
