### ISSUE TITLE
Are projection expressions or similar supported?

### ISSUE THREAD

**Issue by mohan** [Dynamoid/dynamoid#369]
Thanks for this useful gem.

Question: Are projection expressions or any other similar way of fetching only certain attributes supported?

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html

Thank you!

**Comment by andrykonchin** [comment]
This feature isn't supported at the moment but I suppose we could implement it easily in the near future.

**Comment by mohan** [comment]
Thank you!

**Comment by Stevenzhao982** [comment]
Are there any plans for implementing this in the next few weeks or in the next release?

**Comment by andrykonchin** [comment]
@Stevenzhao982 Yes. It definitely will be a part of the next release in August.

**Comment by andrykonchin** [comment]
Done in https://github.com/Dynamoid/dynamoid/pull/374
