### ISSUE TITLE
Typecasting raises exceptions before validations get to run

### ISSUE THREAD

**Issue by sumocoder** [Dynamoid/dynamoid#37]
``` ruby
class User
  include Dynamoid::Document
  field :age, :integer

  validates :numericality => {:allow_blank => true, :only_integer => true }
end

# This is raises an exception about "abc" not being an integer
u = User.new(:age => "abc")
```

ActiveRecord attempts to typecast and if it fails it stores nil. It also stores age_before_type_cast. Something similar needs to be done for Dynamoid.

More info here 
http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/BeforeTypeCast.html

**Comment by andrykonchin** [comment]
Fixed
