### ISSUE TITLE
Config For on-demand, pay-per-request

### ISSUE THREAD

**Issue by davidplappert** [Dynamoid/dynamoid#381]
When I set up the config for dynamoid, it would be nice if I set some attribute that would create the tables as on-demand.

Maybe if I set the read_capacity & write_capacity to 0, have it do that? Or have another boolean attribute on_demand?

**Comment by andrykonchin** [comment]
Yes, it definitely makes sense to have this feature.

I consider adding new config option `capacity_mode` with possible values `provisioned`/`on_demand` like it mentioned in the documentation.

https://docs.aws.amazon.com/en_us/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html

Does it make sense?

**Comment by andrykonchin** [comment]
Implemented https://github.com/Dynamoid/dynamoid/pull/397
