### ISSUE TITLE
Rails 6.0 warning `Module#parent_name`

### ISSUE THREAD

**Issue by benoitongit** [Dynamoid/dynamoid#383]
Not sure if this is already known. When adding this gem to a Rails 6.0 app, starting the server outputs this warning:

DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. `parent_name` is deprecated and will be removed in Rails 6.1. (called from block (2 levels) in require at .rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81)

Hope this helps. Would be amazing to fix :)

Benoit

**Comment by andrykonchin** [comment]
Thank you for reporting the issue. It's already fixed here https://github.com/Dynamoid/dynamoid/pull/382

**Comment by benoitongit** [comment]
BTW, any plan to push this as an official release?

**Comment by andrykonchin** [comment]
No, we don't plan release it right now. It's the only change since last release. Next version will be released in 3 months - in November or so.

IMHO it's completely OK to use current master branch.
