### ISSUE TITLE
Maintenance of Compound Keys for GSI lookups

### ISSUE THREAD

**Issue by arjes** [Dynamoid/dynamoid#389]
A common pattern I have found with DynamoDB is the need to lookup items by a combination of other fields via a GSI, and frequently in a format which doesn't allow a simple GSI on two other fields. 

As a result many of the models I have defined have a macro which essentially performs this function:

```
before_save { self.field_a_and_field_b = "#{feld_a}_#{field_b}" }
```

I've been considering how to better approach this problem. This approach fails when updates are made to the model through methods which bypass the ORM, such as with upserts. Another approach to accomplish my goal would be a more robust `default` value. This would remove the responsibility of maintenance from the ORM.

Is there any interest in enhacning the default value generator to one or both of these options:

```
  field :foo, :string, default: ->(instance) { some_calc_based_on_other_instance_state }
  field :bar, :string, default: :method_name_to_call
```

I reviewed the code, and both of these would require progressively setting the values using the setters, since the current code sets all attributes at once. This also has the side effect of creating weird dependency in the ordering of the `field` declarations.

This is a fairly esoteric request, and if it is unwelcome functionality I'll be happy to keep it as my own patch.

**Comment by andrykonchin** [comment]
Hmm... Am I right, a block/method to calculate default value should have access ideally to all the instance attributes? All the attributes should be loaded from DynamoDB?

If so I don't see how to support this feature for methods, which update items **BUT** don't load item from DynamoDB. You already mentioned `.upsert` method. There are other - `.import`, `update_fields`, `.inc`.

These methods are intentionally so low-level - they provide efficient way to change an item without reading it and adding API call to read an item is a wrong direction.

Have I missed anything?

**Comment by bmalinconico** [comment]
I agree that the complexity around attr accessibility outside of the ORM make not worth the headache to support directly. My ask was more to make the default proc have access to the instance attributes. However after rethinking this I think this is sufficient.

```
class Something
  include Dynamoid::Document

  field :foo
  field :bar
  field :foo_and_bar

  before_save :set_foo_and_bar

end
```

**Comment by bmalinconico** [comment]
Eh, I'm not sure why I can't close this, but feel free to unless you want to discuss this further.

**Comment by arjes** [comment]
Because I was on my work account.
