### ISSUE TITLE
Table keys question 

### ISSUE THREAD

**Issue by emmajhyde** [Dynamoid/dynamoid#390]
Hello,
I have different tables for different environments that need to be dynamically selected, so I cannot use the in-model table field (or can I?). However, this appears to be where I can declare my primary key for the table. Is there any way to declare a primary key that isn't the default 'id' without using the table method, i.e. can I declare that it's the key for the table and declare the table in our AWS config as normal? How can I get around this?

EDIT: also, is there any way to use the native table timestamp management without declaring the name of the table? 

If none of these solutions work, I can just environmentally control the String that we use to declare table name... but I'm curious about the possible implementations anyways.

**Comment by andrykonchin** [comment]
Not sure whether I understand your problem correctly. So provide more details and examples.

> Is there any way to declare a primary key that isn't the default 'id' without using the table method

No.

> i.e. can I declare that it's the key for the table and declare the table in our AWS config as normal?

Yes, you can declare primary key without declaring table name (in `table` method call).

Just to be sure you didn't miss it in the documentation. If a table name isn't specified explicitly (in `table` method) Dynamoid will use table name inferred from a class name. For instance for `User` class default table name will be `users` or `<configured-namespace>_users` where configured-namespace could be `test`, `staging` etc configured globally.

> is there any way to use the native table timestamp management without declaring the name of the table?

What is "native table timestamp management"?

**Comment by emmajhyde** [comment]
Hey, thanks for the quick response! 
Good to know regarding declaring primary key, which also answers my timestamp question (can I use your created_at & updated_at without declaring a tablename), so nevermind that.

As for the table name conversation:
Okay, thank you, I did miss that - so I can configure the config.namespace conditionally based on the environment and I can allow Dynamoid to infer the table name from the environmentalized namespace. Thanks so much for your help!

**Comment by emmajhyde** [comment]
Hello, sorry to reopen, but I'm actually having an issue with our configured namespace. 
```bash
*** Exception Aws::DynamoDB::Errors::ResourceNotFoundException in passenger-irb (Requested resource not found: Table: dynamoid_ContactsCore_production_qa_account_mapping not found) (process 29136, thread 0x007fbf541269a0(IRB worker)):
```
obviously "dynamoid" isn't in our configured namespace... and I am also technically declaring our tablename explicitly here:
```ruby
table name: :qa_account_mapping, key: :account_id
``` 
In your prior comment you mentioned that dynamodb infers the table name if it is not explicitly declared... is there any way to prevent it from doing so in the case that it is?
