### ISSUE TITLE
Dynamoid with an assumed role credential

### ISSUE THREAD

**Issue by emmajhyde** [Dynamoid/dynamoid#391]
Hello,
I was looking at the documentation and couldn’t find anything for this. We have an application that assumes various roles for different aws accounts and resources. I only noticed that dynamoid has the ability to define an access key and secret key. Am I not able to use roles with this gem, given that I am not able to configure the role globally?  Can I give dynamoid a specific client or resource to use that has already had its role configured?
I need something along the lines of:
```ruby
DYNAMO_DB_ROLE_CREDENTIALS = AWS::AssumeRoleCredentials(...)

Dynamoid.configure do |config|
  config.credentials = DYNAMO_DB_ROLE_CREDENTIALS
  config.region = 'us-west-2'
end
```
or: 
```ruby
DYNAMO_DB_ROLE_CREDENTIALS = AWS::AssumeRoleCredentials(...)

Dynamoid.configure do |config|
  config.client = AWS::DynamoDB::Client(
    region: 'us-west-2', 
    credentials: DYNAMO_DB_ROLE_CREDENTIALS
  )
  config.region = 'us-west-2'
end
```
Is there any way I can pass in an option that is not defined in `dynamoid/config.rb` to the client parameters? 
Thank you for your time.

**Comment by andrykonchin** [comment]
Not sure I understand what you want actually.

> Can I give dynamoid a specific client or resource to use that has already had its role configured?

You can provide Dynamoid its specific AWS  credentials (access and secret keys) in this way (from Readme.md):

```ruby
Dynamoid.configure do |config|
  config.access_key = 'REPLACE_WITH_ACCESS_KEY_ID'
  config.secret_key = 'REPLACE_WITH_SECRET_ACCESS_KEY'
  config.region = 'us-west-2'
end
```

> Is there any way I can pass in an option that is not defined in dynamoid/config.rb to the client parameters?

No

> Am I not able to use roles with this gem, given that I am not able to configure the role globally?

What does "globally" mean?

Please let me know if my answer doesn't solve your issue.

**Comment by emmajhyde** [comment]
Okay, it seems like this gem is not compatible with IAM roles - in order to use an AWS IAM role with dynamoid, I have to configure it in the global config, like this: 
```ruby
Aws.config.update({
  region: 'us-west-2',
  credentials: Aws::AssumeRoleCredentials(...)
})
```
but this overrides ALL other credentials for all other AWS applications within my codebase.

 If I configure it for exclusively dynamoid, I can only pass in an access/secret key, I cannot pass in a IAM role credential.

A bummer, I love this gem and I think it is really elegant, but unfortunately we are using mutliple different credentials and roles for different parts of the application. I am unable to configure this in Aws.config.update, nor do I have the access/secret key, I have the role credentials, role arn, etc.

**Comment by andrykonchin** [comment]
I see. Nevertheless it would be great to support this in Dynamoid and the PR is welcomed.

**Comment by emmajhyde** [comment]
https://github.com/Dynamoid/dynamoid/pull/393

**Comment by emmajhyde** [comment]
I would like some attention on the PR that I posted in order to enable this functionality :)

**Comment by emmajhyde** [comment]
Resolved. DynamoID now supports this.
