### ISSUE TITLE
persisted? should not return true if instance has been deleted

### ISSUE THREAD

**Issue by nrowegt** [Dynamoid/dynamoid#411]
```
d = DynamoidModel.upsert(id)
d.destroy!
d.persisted?
=> true
```

Is this intentional to merely check if it's `!new_record?`? https://github.com/Dynamoid/dynamoid/blob/626c33c38471b58c95e4f4c080cb9e5919e362d7/lib/dynamoid/persistence.rb#L285

Happy to open a PR with a fix if the desired behavior is to have `persisted? == false` when an instance no longer exists.

**Comment by andrykonchin** [comment]
Good catch! Yes, it should take into account deleting/destroying.

And the fix is welcome!
