### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by adamthedeveloper** [Dynamoid/Dynamoid#43]
Has anyone been able to get this to run in Rails 5? I just get "There was an error while trying to load the gem 'dynamoid'. (Bundler::GemRequireError)" when I run rails c or rails s.

The error message is unhelpful.

**Comment by abhi-patel** [comment]
Same here.

**Comment by abhi-patel** [comment]
I think this is breaking because of ``include ActiveModel::Serializers::Xml`` in Dynamoid::Components.

Also latest version depends on active_model ~> 4, Any idea when active_model(rails) 5 will be supported?

**Comment by adamthedeveloper** [comment]
I forked the project, commented that Xml line out and changed the version
dependency to >= 4. I also had to fix a null pointer exception to get
around the nil.include? issue that kept popping up if there were no tables
to start with. Take a look at the fork for adamthedeveloper to see the
changes I had to make. I don't know what the impacts of removing the Xml
requirement are yet, however the Gem is working for me now with Rails 5.

**Comment by cignoir** [comment]
+1
Currently, [adamthedeveloper/Dynamoid](https://github.com/adamthedeveloper/Dynamoid) works fine for me in Rails5.
 I will report if it breaks.

**Comment by VGleb** [comment]
+1
[adamthedeveloper/Dynamoid](https://github.com/adamthedeveloper/Dynamoid) works in Rails 5.0.0.beta3

**Comment by cavi21** [comment]
Hey everyone, there is PR #63 opened for this, if anyone has more insight of the issue in order to build a test case for it, it would be great! Happy to do it, or discuss it

**Comment by josephverbeck** [comment]
I also forked the project and worked with the new activemodel-serializers-xml gem to not remove the include ActiveModel::Serializers::Xml from the components.rb file.  This also required updating the activemodel dependency to 5.0.0.beta3.  Hopefully this helps someone else

**Comment by xdougx** [comment]
Is there any changes on dynamoid repository?

**Comment by oklas** [comment]
+1 Is this repository maintained?

**Comment by pboling** [comment]
@xdougx There is at least one PR that attempts to address this.  None of them has been accepted yet.

**Comment by pboling** [comment]
Rails 5 support is done.
