### ISSUE TITLE
Is there a way to query record from certain time rage?

### ISSUE THREAD

**Issue by golodenko** [Dynamoid/dynamoid#436]
It might be stupid question, but cannot figure out how to find records from certain dates range. Or certain day. 

For example form Feb 5 till Feb 7 2020. 

created_at.gt searches from date till end_of_time and created_at.lt searches from date till beginning_of_time and i can't find a way to just limit my search.  And cannon use both cause it it would use only last condition. 

In ActiveRecord this works like charm with simple A..B range as param. Is there something like that in dynamoID?

**Comment by andrykonchin** [comment]
Good question. In this case `between` predicate will work properly:

```ruby
User.where('created_at.between': [Time.now - 1.hour, Time.now])
```

There is an issue with several conditions for the same attribute. `where` uses less powerful and deprecated now `QueryFilter` and similar parameters ([documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#API_Query_RequestSyntax))

Actually it's mentioned in the Readme:
> WARNING: There is a limitation of conditions passed to where method. Only one condition for some particular field could be specified. The last one only will be applied and others will be ignored.

**Comment by golodenko** [comment]
Thats perfect, thank you.
