### ISSUE TITLE
undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by nathantech2005** [Dynamoid/Dynamoid#44]
The save method on the object is raising this error.

**Comment by nathantechie9** [comment]
Also. My test says sqlite is trying to save record. The dynamoid isn't over riding the orm behavior.

class Lead 
  include Dynamoid::Document

  table :name => :leads, :key => :email, :read_capacity => 400, :write_capacity => 400

  field :question
  field :email
  field :created, :datetime, {default: ->(){Time.now}}

  validates_presence_of :lead
  validates_format_of :email, :with => /@/
end

**Comment by adamthedeveloper** [comment]
This is happening when you have no tables to start with. See the changes in my fork: adamthedeveloper. Instead of assuming there are always tables, I set the tables variable to an empty array if it's nil so that the include? still works.

**Comment by nathantechie9** [comment]
Ah ok. Will check it out.

**Comment by adamthedeveloper** [comment]
https://github.com/adamthedeveloper/Dynamoid/commit/19cf5df103ff8598d64f73285021936c045fb969

**Comment by philipmw** [comment]
@adamthedeveloper how about a patch?

**Comment by adamthedeveloper** [comment]
Here you go: https://github.com/Dynamoid/Dynamoid/pull/63

**Comment by pboling** [comment]
This is fixed.
