### ISSUE TITLE
Returning a created_at ordered list

### ISSUE THREAD

**Issue by mooktakim** [Dynamoid/dynamoid#441]
Hi,

I've been trying and I can't seem to figure this out. I am trying to show all items of an object in a list page. I would like to display it in recently created order. I've gone through all the docs, issues and code. I just don't understand.

```
class Company

  include Dynamoid::Document

  table name: :companies
  field :name
  field :user_id
  global_secondary_index hash_key: :user_id, projected_attributes: :all

end
```
Company has timestamp columns, `created_at` and `updated_at`.
When I do `Company.all`, the returned result is in different order. 

Despite some mention of an `order` option in issues, I am not able to find any way to change the order of the returned result. I would like to be able to do this with pagination, which i [managed to make work](https://github.com/Dynamoid/dynamoid#dynamodb-pagination).

This is the first time I'm using DynamoDB/Dynamoid
What am I missing here?

**Comment by andrykonchin** [comment]
DynamoDB cannot return sorted result in general case (like it does any RDMS).

DynamoDB is more like a key-value storage where key is a primary/hash key item attribute and a value is a subtable - items grouped by this primary/hash key attribute.

You can get ordered result only for some particular primary/hash key - items will be sorted by sort/range key (if it's present in a table schema). If a table schema doesn't allow to sort by some particular attribute then there is a solution - indexes (both Global Secondary and Local Secondary indexes).

You can find further information in the official [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html) and [AWS Blog](https://aws.amazon.com/ru/blogs/database/using-sort-keys-to-organize-data-in-amazon-dynamodb/).

**Comment by mooktakim** [comment]
@andrykonchin 
Thank you for the reply.

I'm thinking my solution is to create an index. One thing i don't understand is how do I tell Dynamoid to order based on this index?
I understand there is `scan_index_forward`, but that takes a boolean as a parameter.
If you are able to give me a full example of the query that would be very helpful.

**Comment by andrykonchin** [comment]
> One thing i don't understand is how do I tell Dynamoid to order based on this index?

When you use `where` method Dynamoid selects a proper index automatically (from indexes declared in a model class only). 

DynamoDB returns sorted items only when Query operation is used. Query operation is used only when there is an equality condition on a range key e.g. `where(id: 'abc', ...)` and a range key is declared in a table schema.

> If you are able to give me a full example of the query that would be very helpful.

So let's consider some examples:

```ruby
class ClassWithRangeKey
  include Dynamoid::Document

  range :name
  field :age, :integer
end

ClassWithRangeKey.create(id: 'the same id', name: 'a')
ClassWithRangeKey.create(id: 'the same id', name: 'c')
ClassWithRangeKey.create(id: 'the same id', name: 'b')

# returns collection sorted in ascending order by range key when called with true
models = ClassWithRangeKey.where(id: 'the same id').scan_index_forward(true)
models.map(&:name) # =>  ['a', 'b', 'c']

# returns collection sorted in descending order by range key when called with false
models = ClassWithRangeKey.where(id: 'the same id').scan_index_forward(false)
models.map(&:name) # => ['c', 'b', 'a']
```

```ruby
ClassWithLocalSecondaryIndex do
  include Dynamoid::Document

  range :name
  field :age, :integer

  local_secondary_index range_key: :age, name: :age_index,  projected_attributes: :all
end

ClassWithLocalSecondaryIndex.create(id: 'the same id', age: 30, name: 'a')
ClassWithLocalSecondaryIndex.create(id: 'the same id', age: 10, name: 'c')
ClassWithLocalSecondaryIndex.create(id: 'the same id', age: 20, name: 'b')

# it affects a query
models = ClassWithLocalSecondaryIndex.where(id: 'the same id', 'age.gt': 0).scan_index_forward(false)
models.map(&:age) # => [30, 20, 10]
```
```ruby
ClassWithGlobalSecondaryIndex
  include Dynamoid::Document

  range :name
  field :age, :integer
  field :nickname

  global_secondary_index hash_key: :age, range_key: :nickname, name: :age_nickname_index, projected_attributes: :all
end

ClassWithGlobalSecondaryIndex.create(age: 30, nickname: 'a', name: 'b')
ClassWithGlobalSecondaryIndex.create(age: 30, nickname: 'c', name: 'c')
ClassWithGlobalSecondaryIndex.create(age: 30, nickname: 'b', name: 'a')

# it affects a query
models = ClassWithGlobalSecondaryIndex.where(age: 30).scan_index_forward(false)
models.map(&:nickname) # => ['c', 'b', 'a']
```

**Comment by mooktakim** [comment]
@andrykonchin 
Thats amazing! Thank you for spending so much of your time writing the above.
Will play around with the examples you've given. I believe I know how to solve the issues now.

**Comment by mooktakim** [comment]
I managed to make it work with a `global_secondary_index`. 
I added a GSI for a reference column `user_id` with range_key `created_at`.
It works when I do `where(user_id: "XXXIDXXX").scan_index_forward(true)`
The list is ordered by `created_at` for a specific `user_id`.

I did want to create a full list page without filtering. I don't think this is possible.

I tried to hack it by doing `where("user_id.ne": nil).scan_index_forward(true)`. But that doesn't use the index.

**Comment by andrykonchin** [comment]
Great

> I did want to create a full list page without filtering. I don't think this is possible

If you mean to have **all the stored companies** ordered by some attributes (e.g. created_at) it can be solved with another hack - you need to create a GSI but to use some new attribute with the only one value as a hash key (and created_at as a range key). It means all the items in this GSI will be put into one partition (because there is only one value of our synthetic attribute) and they will be sorted by range key (created_at) but it's definitely a hack.

**Comment by mooktakim** [comment]
Ah you're right! That should work. I see that there has to be a value, can't just be empty or nil.
Thank you, this solves the problem.
