### ISSUE TITLE
Is it possible to not using null-logger gem, because of its license

### ISSUE THREAD

**Issue by yakjuly** [Dynamoid/dynamoid#449]
Hi, I am trying to use dynamoid gem in a commericial project. 

But the company not allowing to use open source libraries that under GPL and LGPL license.

dynamoid is under MIT license, but it is using null-logger and null-logger is under GNU LGPL license. Kind of blocker.

I am thinking since dynamoid doesn't use NullLogger in many places, is it possible to replace it with a customized logger. After that dynamoid can be used in more places.

**Comment by andrykonchin** [comment]
Hmmm. Good point. Never thought about it. A PR with replacing `NullLogger` is welcome.
