### ISSUE TITLE
Range finding doesn't work as documented

### ISSUE THREAD

**Issue by ericpeters0n** [Dynamoid/Dynamoid#46]
For

```
class MyObject
  include Dynamoid::Document
  field :name
end
```

this:

```
MyObject.where("created_at.gt" => DateTime.now - 1.day).all
```

yields

```
ArgumentError: unsupported type, expected Hash, Array, Set, String, Numeric, IO, true, false, or nil, got DateTime
```

Am I missing something?

**Comment by ericpeters0n** [comment]
@sumocoder  - Appreciate your work on the type mappings... Any hints here?

**Comment by ericpeters0n** [comment]
@philipmw - It looks like @sumocoder and @ayemos have PRs that address this breakage to some degree...

**Comment by ericpeters0n** [comment]
Ah, appears this is a result of #17

**Comment by afgarcia86** [comment]
I have the same issue...

**Comment by richardhsu** [comment]
This works now based on @andrykonchin's PR, I've been testing this in a staging environment and it works well.
