### ISSUE TITLE
NoMethodError when trying to add an attribute that isn't on the model

### ISSUE THREAD

**Issue by AlexGascon** [Dynamoid/dynamoid#462]
### Bug description
When using `#update_attributes` to update a field not present in the model, the method completes but trying to save the object raises an error when trying to dump it. The root cause is on [lib/dynamoid/dumping.rb#L6-L41](https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/dumping.rb#L6-L41), because if the attribute is not present in `attributes_options`, the `options` argument passed to `find_dumper` will be `nil`.

While I understand that it may be on purpose to not allow unknown fields on the model, returning a detailed error message will simplify the debugging and result in a better developer experience for Dynamoid's users. I'm happy to prepare a PR to fix the issue, but would like to confirm what should be the expected behavior here: should the error be raised on `#update_attributes`, or would you be fine if the validation and error raising is done on the `Dumping` class directly?

### Steps to reproduce
* **Dynamoid version:** _master_
* **Ruby version:** 2.6.3

I've prepared a small test spec to easily reproduce the error:

```ruby
  describe 'Field that is not declared in the model' do
    it 'raises a NoMethodError' do
      obj = new_class.create
      obj.update_attributes(unknown_field: 'Some value')
    end
  end
```

This is the output:

```ruby
     Failure/Error:
       dumper_class = case options[:type]
                      when :string     then StringDumper
                      when :integer    then IntegerDumper
                      when :number     then NumberDumper
                      when :set        then SetDumper
                      when :array      then ArrayDumper
                      when :map        then MapDumper
                      when :datetime   then DateTimeDumper
                      when :date       then DateDumper
                      when :serialized then SerializedDumper

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/dynamoid/dumping.rb:27:in `find_dumper'
     # ./lib/dynamoid/dumping.rb:17:in `dump_field'
     # ./lib/dynamoid/dumping.rb:9:in `block (2 levels) in dump_attributes'
     # ./lib/dynamoid/dumping.rb:8:in `each'
     # ./lib/dynamoid/dumping.rb:8:in `block in dump_attributes'
     # ./lib/dynamoid/dumping.rb:7:in `tap'
     # ./lib/dynamoid/dumping.rb:7:in `dump_attributes'
     # ./lib/dynamoid/persistence/save.rb:23:in `call'
     # ./lib/dynamoid/persistence/save.rb:8:in `call'
     # ./lib/dynamoid/persistence.rb:483:in `block in save'
     # ./lib/dynamoid/persistence.rb:482:in `save'
     # ./lib/dynamoid/dirty.rb:50:in `save'
     # ./lib/dynamoid/validations.rb:19:in `save'
     # ./lib/dynamoid/identity_map.rb:68:in `save'
     # ./lib/dynamoid/persistence.rb:499:in `update_attributes'
     # ./spec/dynamoid/dumping_spec.rb:1515:in `block (3 levels) in <top (required)>'
     # ./spec/support/unregister_declared_classes.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by andrykonchin** [comment]
Good catch. Any PR is welcome.

I believe error should be raised while unknown attribute is assigning and before dumping. It may be a new error e.g. similar to Rails' `ActiveModel::UnknownAttributeError`:

```
ActiveModel::UnknownAttributeError (unknown attribute 'foo' for AuthToken.)
```

All the Dynamoid error are located here https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/errors.rb

**Comment by AlexGascon** [comment]
I agree, the error on update it's what seems more reasonable. I'll prepare the PR then!
