### ISSUE TITLE
STI: Parent record is not loading data correctly

### ISSUE THREAD

**Issue by murtaza512** [Dynamoid/dynamoid#464]
<img width="547" alt="Screen Shot 2020-07-27 at 1 33 15 PM" src="https://user-images.githubusercontent.com/42164294/88590339-653ffa80-d00f-11ea-9d8d-174af58c5baf.png">

```
(byebug) existing_user = User.where(email: custom_email).count       // 1
0
(byebug) existing_user = Client.where(email: custom_email).count.    // 2
6
(byebug) existing_user = Lawyer.where(email: custom_email).count. // 3
3
(byebug) existing_user = User.where(email: custom_email).count. // 4
9
```

HEre USER is parent table and CLIENT and LAWYER is childs tables 
As you can see in the screenshot. On query 1, it return 0 records and on query 2 and 3 you can see, it returning records and on step 4. Now query 4 also return data and same query 1 does not return data before

**Comment by andrykonchin** [comment]
Looks like the issue is related to classes lazy loading.

Could you check whether classes `Client` and `Lawyer` are loaded before "query 1"? If they aren't - it's completely expected behavior that unknown/not loaded child classes are ignored when parent class is used.

**Comment by murtaza512** [comment]
Yes. I think so @andrykonchin
