### ISSUE TITLE
`delete_all` and `destroy_all` not available as class methods

### ISSUE THREAD

**Issue by ProGM** [Dynamoid/dynamoid#465]
The docs states that `delete_all` and `destroy_all` should work also as class method, to remove all items from the table:

https://github.com/Dynamoid/dynamoid/blob/master/lib/dynamoid/criteria/chain.rb#L222

However, I've tried `Post.delete_all` and I get this error:

```ruby
undefined method `delete_all' for Post:Class
```
The same for `destroy_all`

I'm using Dynamoid 3.6.0.

**Comment by andrykonchin** [comment]
Nice catch. It's a bug so will fix it soon.

**Comment by ProGM** [comment]
I've found a temporary workaround: `Post.where({}).delete_all` seems to do the trick.
