### ISSUE TITLE
Feature Request: Custom field name

### ISSUE THREAD

**Issue by darkash** [Dynamoid/dynamoid#466]
I think this will be helpful for migrating/upgrading from legacy code or to move away from another language. The main reason for this is naming convention.

Use case:
Database fields:
```
id: string
createdAt: datetime
updatedAt: datetime
name: string
secondaryName: string
```

In this case, the code would be
```
class User
  include Dynamoid::Document

  table name: :users, key: :id
  field :name, :string
  field :secondaryName, :string
  field :createdAt, :datetime
  field :updatedAt, :datetime
  field :id, :string
end
```
What I would like to achive is something like:
```
class User
  include Dynamoid::Document

  table name: :users, key: :id
  field :name, :string
  field :secondary_name, :string, field_name: :secondaryName
  field :created_at, :datetime, field_name: :createdAt
  field :updated_at, :datetime, field_name: :updatedAt
  field :id, :string
end
```

This way, it makes it easier to maintain naming convention in new code without turning off the linter rule if there's a project using it. It also makes the code less ugly with mixed up camel-case and snake-case naming convention.

**Comment by andrykonchin** [comment]
Yeah, it sounds good.

There is a similar approach in Rails with [alias_attribute](https://api.rubyonrails.org/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-alias_attribute) method. TBH I cannot decide which one is better.

**Comment by darkash** [comment]
> Yeah, it sounds good.
> 
> There is a similar approach in Rails with [alias_attribute](https://api.rubyonrails.org/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-alias_attribute) method. TBH I cannot decide which one is better.

yea, for now I used plain ruby alias/alias_method to define it, but the problem is the setter method, defining aliases for both setter and getter is quite an effort without generating it programatically. But that's just how far I can do right now :)
========
as for the approach, I think alias_attribute would be good enough.

**Comment by andrykonchin** [comment]
I believe we can have both mechanisms as far as they complement one another.
