### ISSUE TITLE
Parent association record of object that :belongs_to another object not deleted on object delete/destroy

### ISSUE THREAD

**Issue by mitchellharper12** [Dynamoid/dynamoid#467]
Rails version: 6.0.3.2
Dynamoid version: 3.6.0

Expected behavior:

When I delete or destroy an object of type Child that belongs to another object Parent, and Parent has many Child objects, the foreign key on the parent association record is deleted

Actual behavior:

The foreign key is not deleted, and trying to resolve elements in e.g. Parent.find(id).users results in an error like the following

```
Dynamoid::Errors::RecordNotFound (Couldn't find all Users with primary keys [d203aa5e-78ab-4763-ad7f-2636311a2e42] (found 0 results, but was looking for 1))
```

Will try and get to the root of the issue myself and add a PR if I can.

**Comment by andrykonchin** [comment]
Nice catch.

Yeah, looks like associations aren't updated when document is deleted/destroyed. Any PR is welcome 👍 .
