### ISSUE TITLE
problem querying against a GSI, with created_at in the sort key

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#479]
Thanks for being so responsive in these git issues! They have been very helpful.

```
class MyTable
  include Dynamoid::Document

  table name: :MY_TABLE, key: :id, capacity_mode: :on_demand
  range :another_id

  # `created_at` is a Dynamoid autogenerated number like `1602669126.609105167`
  global_secondary_index name: 'MY_INDEX', hash_key: :id, range_key: :created_at, projected_attributes: :all, capacity_mode: :on_demand
end
```

I want to query against `MY_INDEX` via `id`, sorted by the creation date.

If I query with `MyTable.where(id: '123').scan_index_forward(false)`, the criteria chain returned doesn't seem to detect the GSI.

If I query with `MyTable.where(id: '123', 'created_at.gt': 0).scan_index_forward(false)`, then the criteria chain does seem to return the GSI, eg. ` @result={:hash_key=>:id, :range_key=>:created_at, :index_name=>"MY_INDEX"}`.

However, executing the query results in: `Aws::DynamoDB::Errors::ValidationException (One or more parameter values were invalid: ComparisonOperator GT is not valid for NULL AttributeValue type)`

I added the `'created_at.gt': 0` field so that Dynamoid can detect the index. I also tried `'created_at.not_null: true'`, and variants like this. But I just want to query on `id` against the index, sorted by the creation date field.

Can you advise?

**Comment by andrykonchin** [comment]
There is a not released yet feature to force index in Scan/Query operations (https://github.com/Dynamoid/dynamoid/pull/476). In your example  (on the Dynamoid current master branch) it could look like:

```ruby
MyTable123.where(id: '123').scan_index_forward(false).with_index(:MY_INDEX)
```

> If I query with MyTable.where(id: '123', 'created_at.gt': 0).scan_index_forward(false), then the criteria chain does seem to return the GSI, eg. @result={:hash_key=>:id, :range_key=>:created_at, :index_name=>"MY_INDEX"}.

> However, executing the query results in: Aws::DynamoDB::Errors::ValidationException (One or more parameter values were invalid: ComparisonOperator GT is not valid for NULL AttributeValue type)

I suppose it's pretty expected result (but error message could be more friendly). The issue is that values are type casted by Dynamoid and in `'created_at.gt': 0` expression `0` is invalid value for `datetime`. `Time.at(0)` should be used instead to force index.

**Comment by rhuang** [comment]
Great, thanks. I've tested both and they work! Closing.
