### ISSUE TITLE
Model.find raise error in test env

### ISSUE THREAD

**Issue by icotanchev** [Dynamoid/dynamoid#486]
In our project, we have a simple table using DynamoDB. We are using the `find` method to find the record and It works fine in production and development ENVs but in test env, it raises a strange error about `undefined method `to_sym' for nil:NilClass` in `gems/dynamoid-3.6.0/lib/dynamoid/adapter_plugin/aws_sdk_v3.rb:567:in `key_stanza'`. In the spec_helper we have `Aws.config[:dynamodb] = { stub_responses: true }` to stub the responses.

**Comment by andrykonchin** [comment]
Could you please provide an example of test to reproduce the issue?

**Comment by andrykonchin** [comment]
I've reproduced the issue and I wouldn't consider it as a bug in Dynamoid.

Dynamoid relies on a table schema declared in a model class (range and hash keys at least). But there are some places when Dynamoid loads actual table meta information with DescribeTable api call ([documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTable.html)).

As far as I understand stubbing client responses with `Aws.config[:dynamodb] = { stub_responses: true }` approach actually stubs all the communication with DynamoDB. AWS SDK returns some dummy data with correct structure. And DescribeTable is stubbed as well. But Dynamoid expects that a response object contains table schema - hash and range attribute names. So missing table schema in stubbed response leads to the reported exception.

Example of the stubbed response for the DescribeTable api call which AWS SDK returns in "stub_responses" mode:

<img width="815" alt="Screen Shot 2021-01-29 at 10 49 11 PM" src="https://user-images.githubusercontent.com/732181/106325893-42272980-6284-11eb-83a7-70979a01b66c.png">

A real table schema looks like this one:

<img width="815" alt="Screen Shot 2021-01-29 at 10 48 48 PM" src="https://user-images.githubusercontent.com/732181/106325890-3fc4cf80-6284-11eb-9b3f-7813d017262c.png">

As you can see stubbed response contains empty key schema - `key_schema=[]`.

So what options I could suggest.

1. It's possible not to load table definitions at all and to rely completely on a schema declared in a model class. But generally speaking I think it's too strict constrain and would prefer other options. I can imagine cases and features when loading actual table description will be very useful. 
2. As a workaround if in tests DynamoDB is completely stubbed - DescribeTable api call may be also stubbed either with mock library (e.g. rspec-mock) or with already mentioned `Aws.config[:dynamodb] = { stub_responses: true }` approach. 

DescribeTable call can be stubbed this way:

```ruby
Aws.config[:dynamodb] = {
  stub_responses: {
    describe_table: {
      table: { :key_schema=>[{ attribute_name: 'id', key_type: 'HASH' }] }
    }
  }
}
```

 I checked and `find` works well and return a dummy model.

**Comment by icotanchev** [comment]
Hi @andrykonchin. Thanks for fist replay and provided solution, it works for us :)
