### ISSUE TITLE
Is it not possible to Query with a FilterExpression?

### ISSUE THREAD

**Issue by rahsheen** [Dynamoid/dynamoid#494]
I have a GSI setup on my table, which is working well with `where` when I specify the correct hash and range keys. 

I naively expected that something like `Foo.where(bar: 1, baz: Time.now).where(boppety: 23)`  would take my GSI and then apply a FilterExpression on the Query using the last `where` clause.

What actually happens is, the `TableName` changes back to the primary (no longer using GSI) and I guess it does a Scan instead.

Is it possible to do FilterExpressions with Dynamoid on a GSI?

**Comment by andrykonchin** [comment]
Yes, it's possible to use Query operation (and consequently the FilterExpression) with GSI and it should work out of the box.

Could you please provide full example (with model class definition with GSI and hash/range keys) and `where` expressions one of which works well and other doesn't to reproduce the issue?

**Comment by rahsheen** [comment]
```
class Dynamodb::BlahCycle < DynamoidDocument
  include Dynamoid::Document

  table name: :blah_cycle, key: :blah_id, read_capacity: 50, write_capacity: 50
  range :started_at, :datetime, store_as_string: true

  field :duration, :integer, default: 0
  field :blah_id, :integer
  field :bippety_id, :integer
  field :data, :raw, default: {}

  global_secondary_index hash_key: :bippety_id, range_key: :started_at, projected_attributes: :all
```

This correctly uses the GSI:
` Dynamodb::BlahCycle.where(bippety_id: 1, 'started_at.gt': Time.now - 2.weeks)`

This _does not_ use the GSI at all, but _does_ seem to do a `QueryFilter`:
` Dynamodb::BlahCycle.where(bippety_id: 1, 'started_at.gt': Time.now - 2.weeks).where(blah_id: 1)`

**Comment by rahsheen** [comment]
After digging into the code a bit, I could tell that adding the table `hash_key` to the query (to be used for the filter_expression) was just confusing the `KeyFieldsDetector` into just using the primary hash/range keys. I had to upgrade to 3.7 and use `with_index`. This _seems_ to have resolved the issue.

**Comment by rahsheen** [comment]
I know that `with_index` is a solution, but didn't want to close this before seeing if there are any alternatives and confirming that this is actually expected behavior. 

I'm fully willing to accept that I might be doing something wrong. 😃

**Comment by andrykonchin** [comment]
As far as I understood the issue is following:
- when `where` conditions contain a table hash and range keys and GSI hash and range keys
- then Dynamoid decides to do Query on a table
- but preferable operation is Query on a GSI.

It looks like an expected behavior. Looking at a table schema it isn't possible to decide which option is better - they all are good enough as far as they lead to Query operation.

**Comment by rahsheen** [comment]
Awesome, just wanted to check. Thanks for your help! @andrykonchin
