### ISSUE TITLE
does .project work with .find?

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#499]
`User.where(email: email).project(:some_field).first` works as expected, returning the `User` object with only `some_field`.

However, `User.project(:some_field).find(id)` returns an `Enumerator`. Is this correct?

Looking through `Dynamoid` it looks like `project` was only added for queries and not for `find` (`getItem`), but I believe that projection expression is available for `getItem`: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html

**Comment by andrykonchin** [comment]
Yeah, right now `find` and `find_all` methods aren't available for the chaining methods e.g. `where`/`project`/etc and it definitely makes sense to support both cases:
- with filtering (`where(...).find(...)`)
- and without, e.g. `project(...).find(...)`

Will add this feature to the next release plan.

**Comment by rhuang** [comment]
@andrykonchin 

If I run something like:

```
class User
  include Dynamoid::Document
  table name: :USERS, key: id

  field: email
  field: column_1
  field: column_2
end

user = User.create(id: '1', email: 'test@test.com', column_1: 'some', column_2: 'thing')
user = User.project(:id, :email, :column_1).where(id: '1').first
user.save 
```

After saving the projected model, `column_2` is now nil (`column_2` wasn't projected). Is this expected behavior?

**Comment by andrykonchin** [comment]
I would consider it as expected behavior. AFAIK in Rails such model saving will not update the record at all (because it updates only changed "dirty" attributes) but I would say it's just an optimization.

But it will be a good improvement to save only changed attributes. Will add to the roadmap.

**Comment by rhuang** [comment]
Yes, this would be good to add. It is risky to project a model and ensuring it is only read from. Someone else can add code to `save` the model without realizing it is a projected model, which will set the non-projected fields to `nil`.

**Comment by andrykonchin** [comment]
Saving only changed attributes is merged (https://github.com/Dynamoid/dynamoid/pull/623)
