### ISSUE TITLE
Provide option to skip namespace in configuration

### ISSUE THREAD

**Issue by BilalBudhani** [Dynamoid/Dynamoid#5]
I've been rewriting a legacy app in Ruby. When I try to provide a custom name to my table name Dynamoid prepends namespace to the table name. It would be great if we can skip namespace in configuration. I also tried leaving the namespace blank which results in `_` before the table name.

**Comment by RedaBenh** [comment]
+1
i try to name my table "my_table". but i can't because the gem set it to "_my_table" !

**Comment by cignoir** [comment]
+1
I hope this gets fixed.

**Comment by philipmw** [comment]
I merged the fix, thanks to brenden.
