### ISSUE TITLE
Tokenizer not supported in validations

### ISSUE THREAD

**Issue by thomaswitt** [Dynamoid/dynamoid#502]
In ActiveRecord you can do validations using a tokenizer, like checking for number of words:

```
class Essay < ActiveRecord::Base
  validates :content, length: {
    minimum: 300,
    maximum: 400,
    tokenizer: lambda { |str| str.scan(/\w+/) },
    too_short: "must have at least %{count} words",
    too_long: "must have at most %{count} words"
  }
end
```
(Source: https://guides.rubyonrails.org/v4.1/active_record_validations.html#length)

Unfortunately tokenizer's apparently don't work with Dynamoid? At least, when I try this code, it doesn't work at all, only the char length is checked with minimum/maximum.

**Comment by andrykonchin** [comment]
Dynamoid uses `ActiveModel::Validations` as is so validation should behave as it does in ActiveRecord. As far as I understand the `tokenizer` option was deprecated in Rails 5.0 and removed completely in Rails 5.1.

https://github.com/rails/rails/blob/main/guides/source/5_1_release_notes.md#active-model

**Comment by thomaswitt** [comment]
My bad, sorry for this. This works just fine:

```
  validates_length_of :words_in_content, minimum: 4,
    too_short: I18n.t(:too_short),
    too_long: I18n.t(:too_long)

  def words_in_content
    content.scan(/\w+/)
  end

```
