### ISSUE TITLE
Amazon DynamoDB now supports empty values.

### ISSUE THREAD

**Issue by yubele** [Dynamoid/dynamoid#504]
Dynamoid doesn't seem to support empty fields. DynamoDB started supporting empty fields on 05/2020.

Are you planning to support empty fields with Dynamoid? Also, are there any existing features like that? 

ref) 
https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/?nc1=h_ls

**Comment by andrykonchin** [comment]
Yeah, it's in the roadmap. But it's a breaking change and will be released only in the next major version.

**Comment by yubele** [comment]
@andrykonchin Thank you for your information. I will wait for the next major version.

**Comment by andrykonchin** [comment]
The issue is resolved in #794
