### ISSUE TITLE
support for atomic increment?

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#505]
Is this going to be supported?

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters

**Comment by andrykonchin** [comment]
It's already supported with `.inc` method:

```ruby
User.inc('1', 'Tylor', age: 2)
```

https://github.com/Dynamoid/dynamoid/blob/v3.7.0/lib/dynamoid/persistence.rb#L356-L395

**Comment by rhuang** [comment]
Thanks!
