### ISSUE TITLE
The default behaviour of Boolean fields is changed with Version 3

### ISSUE THREAD

**Issue by Ashish-Jaiswal98** [Dynamoid/dynamoid#515]
Hi
I am trying to update my package dependency from AWS SDK version 2, Dynamoid version 2 to latest v3.
I noticed the default behaviour of boolean fields are changed. Earlier they used to get saved as string 't'/ 'f'. Now the default behaviour is to save in DynamoDb as boolean true/ false. I found there is a way to prevent this behaviour by using  store_as_native_boolean: false. https://github.com/Dynamoid/dynamoid#note-on-boolean-type.
My package has lot of model files which uses boolean fields. Is it possible to prevent this new default behaviour of setting as boolean instead of string at global level. By setting this flag in some config file.

**Comment by andrykonchin** [comment]
Yeah, there is a global config option `store_boolean_as_native` ([documentation](https://github.com/Dynamoid/dynamoid#configuration)). It was added in the 3.0.0 version ([changelog](https://github.com/Dynamoid/dynamoid/blob/master/CHANGELOG.md#300))

**Comment by Ashish-Jaiswal98** [comment]
Thanks for the help. Closing the issue.
