### ISSUE TITLE
How to avoid detecting mutation when Updated the same value

### ISSUE THREAD

**Issue by a5-stable** [Dynamoid/dynamoid#524]
Hi team, as you might know, 
Dynamoid::Dirty returns the different result from ActiveModel::Dirty.

I prepare person model whose name is Bob.
> person.name # => "Bob"

When checking dirty api after re-assigning the same value（Bob),  I got unexpected results.
```
# Dynamoid::Dirty

person.name = "Bob"
person.changed?
=> true

person.changes
=> {"name" => ["Bob", "Bob"]}
```

On the other hand, ActiveModel::Dirty returns
https://github.com/rails/rails/blob/9334223c51839addb5bbf7c61f33644f250999a1/activerecord/lib/active_record/type/value.rb#L71
```
# ActiveModel::Dirty

person.name = "Bob"
person.changed?
=> false

person.changes
=> {}
```

Is this by design? Is there any way to avoid unintuitive result?

**Comment by andrykonchin** [comment]
Hello.

Am I right you are talking about this use-case?

```ruby
u = User.new(foo: 'bar')
u.save
u.foo = 'bar'
u.changes
# => {"foo"=>["bar", "bar"]}
```

It isn't intentional behavior and should be changed to mimic ActiveRecord.

**Comment by a5-stable** [comment]
@andrykonchin 
Thank you for quick reply.
Yes, you're right.

I made a draft-pr to solve it in a very simple way.
#525

**Comment by andrykonchin** [comment]
Looks good. I have left some comments.

**Comment by a5-stable** [comment]
@andrykonchin 
Thank you so much. I fixed [it](https://github.com/Dynamoid/dynamoid/pull/525).
