### ISSUE TITLE
run update callback by using `#update_attributes`

### ISSUE THREAD

**Issue by a5-stable** [Dynamoid/dynamoid#530]
Greetings, 
I'm using `#update_attributes` to update a record 
and it doesn't run callback such as `before_update` and `after_update`.

Should I use `#update` to make use of the update callbacks? 

or, I may be able to add `run_callbacks(:update) ` to `#save`.
It would be as below: 

```
    def save(options = {})
      self.class.create_table(sync: true)

      @_touch_record = options[:touch]

      if new_record?
        run_callbacks(:create) do
          run_callbacks(:save) do
            Save.call(self)
          end
        end
      else
        run_callbacks(:update) do # here
          run_callbacks(:save) do
            Save.call(self)
          end
        end
      end
    end
```

**Comment by andrykonchin** [comment]
Dynamoid is missing right now the update callback. But it will be great to have it.

So right now there are two options:
- to use save callback or
- to monkey-patch the `def save(options = {})` method like in the provided code snippet.

**Comment by a5-stable** [comment]
@andrykonchin 
Thank you for your reply 🙇‍♀️ 
Since `#update` seems to have the update callback, I guess `#save` can also have the update callback.
I try implementing it in #531, so please use it if you like ( and feel free to close it when you don't need it. )

Please let me know if there is something that needs to be fixed, thanks.

**Comment by andrykonchin** [comment]
Thank you for the fix. Merged.
