### ISSUE TITLE
A proposal of a shorter key definition

### ISSUE THREAD

**Issue by cignoir** [Dynamoid/Dynamoid#54]
When we define hash_key and range_key with some types, we have to write as bellow:
```
class Comment
  include Dynamoid::Document

  table :name => :comment , :key => :user_id, :range_key => :comment_id
  range :comment_id, :integer

  field :user_id, :integer
end
```
This notation is a little redundant. I would rather write as:
```
class Comment
  include Dynamoid::Document

  table :name => :comment
  
  hash_key :user_id, :integer
  range_key :comment_id, :integer
end
```

**Comment by cignoir** [comment]
This is a sample implementation of the proposal.
https://github.com/cignoir/Dynamoid/commit/bc0773086aefa7e16fa93f5d08117b03fc3efcdf

To avoid the collisions of key names, I used ```partition_key/sort_key``` instead of ```hash_key/range_key``` experimentally.

Thanks.

**Comment by philipmw** [comment]
I agree it's better. Not sure I agree that it's worthwhile.

**Comment by cignoir** [comment]
I think [aws-sdk-ruby-record](https://github.com/aws/aws-sdk-ruby-record) has better DSL than my example and I know it is too expensive that implementing a new DSL for Dynamoid.
