### ISSUE TITLE
Aws::DynamoDB::Errors::ValidationException on presence validation

### ISSUE THREAD

**Issue by kazzix14** [Dynamoid/dynamoid#553]
Hi, I have a model that validates presence of association.
```ruby
class ModelA
  include ApplicationRecordable

  table name: :model_a, key: :id
  
  belongs_to :model_b, inverse_of: :model_a

  validates :model_b, presence: true
end
```
When I `save` ModelA with invalid foreign key, I get an exception: `Aws::DynamoDB::Errors::ValidationException`.  
I think `save` should return boolean and add an error to the model instead of raising an exception.
```ruby
model_a = ModelA.new(model_b_id: "")

# this raises `Aws::DynamoDB::Errors::ValidationException in  ModelAController#create: One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value. Key: id`
model_a.save
```

**Comment by kazzix14** [comment]
I'm not sure what that is, but something fixed this. I close this issue, because this doesn't seem to be cause by dynamoid.

**Comment by kazzix14** [comment]
I can avoid exception by check existence of the id before validation 
```ruby
validates :model_b, presence: true, if: -> { self.model_b_id.present? }
```  
 but this should be done by dynamoid I think?

**Comment by andrykonchin** [comment]
Assigning associated model doesn't work in this way (by setting id attribute):
```ruby
model_a = ModelA.new(model_b_id: "")
```

A model object should be specified instead:

```ruby
model_a = ModelA.new(model_b: b)
```

If you look at how Dynamoid stores a foreign key you will see that it's a Set:

```ruby
class A
  include Dynamoid::Document
end

class B
  include Dynamoid::Document

  belongs_to :a
end

a = A.create
b = B.new(a: a)
b.save

p b.attributes

#=> {:a_ids=>#<Set: {"e77d6f95-3743-44ea-a8a3-1a1ea2667802"}>, :created_at=>Sun, 15 May 2022 15:32:21 +0300, :updated_at=>Sun, 15 May 2022 15:32:21 +0300, :id=>"952bf50b-38dc-4c33-8d18-004d83c9d64d"}
```

And there is attribute `a_ids ` instead of `a_id`

**Comment by kazzix14** [comment]
I think I omitted too many thing.  `foreign_key: :model_b_id` is specified and the key is defined with `field :model_b_id, :string`, and it's working except for presence validation.  



> A model object should be specified instead:
> `model_a = ModelA.new(model_b: b)`  

I changed model instantiation to use model object instead of id, now it's working. Thank for your help!
