### ISSUE TITLE
A question about ttl

### ISSUE THREAD

**Issue by ribarbosa** [Dynamoid/dynamoid#563]
Hi, folks
A have a table with ttl config, but I`m dealing with some stranger things here (at least for me).

1 - When I run in development mode, even if I set a time to ttl expire a record, the records aren`t be destroyed.
2 - When I run in test mode and set a breakpoint (using pry, for example) in the code, regardless ttl value, this records are be destroyed immediately.
3 - When I run in test mode (without breakpoint), using Timecop to travel in time, the records aren't be destroyed (like in development mode).

Here its my code:
```ruby

module Dynamodb
  class Coupon
    include Dynamoid::Document
    
    table name: :coupon, key: :id, capacity_mode: :on_demand, expires: { field: :ttl, after: 60 }

    field :offer_id, :string
    field :consumer_id, :string
    field :merchant_id, :string
    field :coupon_key, :string
    field :sent_at, :string
    field :value_in_cents, :string
    field :ttl, :integer
    field :expiration_at, :integer
    
    global_secondary_index name: 'coupon_key', hash_key: :coupon_key, projected_attributes: :all
  end
end
```

Does anyone have an idea about this?

**Comment by andrykonchin** [comment]
> if I set a time to ttl expire a record, the records aren`t be destroyed.

Do I understand you correctly, items in a table isn't deleted after expiration interval (`TTL`), but they are supposed to?

**Comment by ribarbosa** [comment]
Sure!

For example, here I'm running in test environment, using dynamodb-local (with docker)

```shell
[1] pry(#<OffersStore::Actions::BuildConsumersCoupons>)> create_on_dynamodb(key_consumer_offer, expiration_at_seconds)
=> #<Dynamodb::Coupon:0x00007fc6a7119778
 @_touch_record=nil,
 @associations={},
 @attributes=
  {:coupon_key=>"1:4483:2183", :expiration_at=>1602730799, :created_at=>Sat, 10 Oct 2020 17:00:00 -0300, :updated_at=>Sat, 10 Oct 2020 17:00:00 -0300, :id=>"e07a87d4-4d87-430c-a57a-2975644ad311"},
 @attributes_before_type_cast=
  {:coupon_key=>"1:4483:2183",
   :expiration_at=>1602730799,
   :created_at=>Sat, 10 Oct 2020 17:00:00 -03 -03:00,
   :updated_at=>Sat, 10 Oct 2020 17:00:00 -03 -03:00,
   :id=>"e07a87d4-4d87-430c-a57a-2975644ad311"},
 @changed_attributes={},
 @errors=#<ActiveModel::Errors:0x00007fc6a69d1100 @base=#<Dynamodb::Coupon:0x00007fc6a7119778 ...>, @details={}, @messages={}>,
 @new_record=false,
 @previously_changed=
  {"coupon_key"=>[nil, "1:4483:2183"],
   "expiration_at"=>[nil, 1602730799],
   "created_at"=>[nil, Sat, 10 Oct 2020 17:00:00 -0300],
   "updated_at"=>[nil, Sat, 10 Oct 2020 17:00:00 -0300],
   "id"=>[nil, "e07a87d4-4d87-430c-a57a-2975644ad311"]},
 @validation_context=nil>
[2] pry(#<OffersStore::Actions::BuildConsumersCoupons>)> Dynamodb::Coupon.last
=> nil
```

My coupon was created, but then I call Dynamodb::Coupon.last and its return nil

My Gemfile:


```ruby
gem "aws-sdk-rails", "~> 3.2.1"
gem "aws-sdk-s3", "~> 1.84"
gem "aws-sdk-secretsmanager", "~> 1.43.0"
gem "aws-sdk-sns", "~> 1.43.0"
gem 'aws-record', '~> 2.0'
gem 'dynamoid', '~> 3.7', '>= 3.7.1'
```

My docker-compose

```docker-compose
dynamodb-local:
    # dbPath doesn't work in Github CI
    # command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  ```

**Comment by andrykonchin** [comment]
1) DynamoDB doesn't promise to delete items with TTL immediately after expiration:

> Because TTL is meant to be a background process, the nature of the capacity used to expire and delete items via TTL is variable (but free of charge). TTL typically deletes expired items within 48 hours of expiration

https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/howitworks-ttl.html

2) I checked how TTL works with `dynamodb-local` and it doesn't delete an expired item even after several minutes after expiration. So probably it's expected behavior.

3) To be able to debug you issue - please set `debug` level of logging and provide plz the logs when you reproduce the issues

```ruby
Dynamoid.logger.level = :debug
```

To log not only requests but also responses - please set log formatter in the following way (in Rails initializer or wherever before any request to DynamoDB happens):

```ruby
require 'dynamoid/log/formatter'
Dynamoid.config.log_formatter = Dynamoid::Log::Formatter::Debug.new
```
