### ISSUE TITLE
Any chance to cut a more recent release?

### ISSUE THREAD

**Issue by mastamark** [Dynamoid/dynamoid#597]
Looks like the most recent release is from 2021 - https://github.com/Dynamoid/dynamoid/tags - any chance we can cut at least a minor release in the near future?  🙏

**Comment by andrykonchin** [comment]
Hey. The next release is already prepared (https://github.com/Dynamoid/dynamoid/pull/592) - I need only to publish it. Will do it within the next several days.

**Comment by mastamark** [comment]
Thank you very much!

**Comment by xeger** [comment]
Good to hear; thank you so much @andrykonchin for your work on this gem!

**Comment by andrykonchin** [comment]
I've just released [v3.8.0](https://rubygems.org/gems/dynamoid/versions/3.8.0). Sorry for such delay.
