### ISSUE TITLE
Range finding functionality ('field.gt' et al) works only for Query, not Scan

### ISSUE THREAD

**Issue by philipmw** [Dynamoid/Dynamoid#6]
AWS SDK v2 supports an optional `scan_filter` on Scan API calls, with the same semantics as `query_filter` on Query API calls.

Dynamoid offers convenience methods for finding on range fields, such as `my_chain.where("rangefield.gt" => 5)`, but it works only on Query API calls. On Scan, Dynamoid _allows_ this query chain, but it does not translate the ".gt" component, so you end up scanning for a non-existent field.

We need the range finding functionality to be consistent between Query and Scan.

**Comment by afgarcia86** [comment]
Any update on this?

**Comment by pboling** [comment]
@afgarcia86 this is supported in the latest master.  A new release will be out soon.
