### ISSUE TITLE
Invalid item size limit calculations and MAX_ITEM_SIZE value

### ISSUE THREAD

**Issue by activefx** [Dynamoid/Dynamoid#60]
Dynamoid sets the `MAX_ITEM_SIZE` value to 64 KB. However, the current limit is 400 KB. Please see the [Limits in DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-items) documentation. 

Also, the `#write_attribute` method within `Fields` incorrectly calculates this limit. 

``` ruby
def write_attribute(name, value)
  if (size = value.to_s.size) > MAX_ITEM_SIZE
    Dynamoid.logger.warn "DynamoDB can't store items larger than #{MAX_ITEM_SIZE} and the #{name}  field has a length of #{size}."
  end
...
```

The calculation for the warning only takes into account the size of a single value. However the item limit is based upon the sum of all key value pairs within the item. If you wanted to keep the warning, to be accurate, the calculation would have to be something like: 

``` ruby
attributes.map{|k,v| "#{k}#{v}"}.join.size
```

I can submit a pull request if you let me know the direction you would like to take.

**Comment by pboling** [comment]
Pull requests, and advice are appreciated.  This project is now under new maintainers.  What do *you* think would be the best way to fix this?

**Comment by andrykonchin** [comment]
Done
