### ISSUE TITLE
DynamoDB Expensive cost caused by the value 400 in read and write capacity 

### ISSUE THREAD

**Issue by RedaBenh** [Dynamoid/Dynamoid#61]
Hi,

I try this gem few months ago. I follow the examples in the documentation (readme) to create dynamoDB  tables. But at the end of each month i get an expensive cost (+200$) caused by the tables created with your examples with 400 for read and write capacity. 
(I forget to delete these tables because i change the region in AWS and the tables ware hidden :-( ) .

I suggest to change the capacity in your documentation to a lower value like 1 or 2. Users can adjust this value if needed.

```
class User
  include Dynamoid::Document
  table :name => :awesome_users, :key => :user_id, :read_capacity => 2, :write_capacity => 2
end
```

Thanks

**Comment by cignoir** [comment]
That was very sad incident ;(

**Comment by philipmw** [comment]
That's awful. So sorry about that!

If you contact AWS Support, they'll probably refund you. They're very reasonable people.

**Comment by RedaBenh** [comment]
Thank you for your quick answer and for your update of readme pages.
I logged a case to AWS support, i hope they understand and refund me.
