### ISSUE TITLE
Testing Rails apps on Dynamoid-- How??

### ISSUE THREAD

**Issue by ericpeters0n** [Dynamoid/Dynamoid#67]
At present, I'm hacking around trying to figure out how to test my Rails app built on Dyanmoid/Dynamo... not intuitive.

Any suggestions from the pros? Thanks!

(I'm happy to consolidate suggestions and add to the README!)

**Comment by cavi21** [comment]
Hi @ericpeters0n not sure what's the issue here? What are you trying to achieve and seems not possible?

**Comment by cavi21** [comment]
Hey @ericpeters0n any news on this? or any doubt?

**Comment by bglusman** [comment]
@ericpeters0n have you tried using dynamodb-local ?  that would certainly help testing

**Comment by ericpeters0n** [comment]
In case my situation wasn’t clear, I needed to create using and functional tests for my app running on Dynamoid/DynamoDB

Some of the Rails testing frameworks (e.g. Minitest) presume that a valid schema.db will be available to bootstrap testing. Thus, using Dynamoid’s :field definitions isn’t sufficient. (Whether you run DynamoDB locally or on AWS makes no difference here.)

While you can duplicate the schema in a local database (e.g. SQLite) or even just manually create a valid schema with the corresponding types, you can also hack around these requirements by cherry-picking what test_helper.rb attempts to load.

```
# test/
#
test_helper.rb
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)

# This is the standard setup for Rails 4 tests… but won’t work without a valid schema.db
# require 'rails/test_help’ 

# require 'minitest'
# require 'minitest/autorun'

# Instead, cherry-pick the libraries that rails/test_help.rb attempts to load:
require 'active_support/testing/autorun'
# require 'active_support/test_case'
require 'action_controller'
require 'action_controller/test_case'
require 'action_dispatch/testing/integration'
require 'rails/generators/test_case'

…
```

You must also avoid using fixtures if you go this route, but this is manageable.

If we wanted to get fancy and address this in Dynamoid, we could monkey-patch test_helper so read the available models and create a schema on the fly prior to testing… 



On May 16, 2016 at 11:39:37 AM, Brian Glusman (notifications@github.com) wrote:

@ericpeters0n have you tried using dynamodb-local ? that would certainly help testing

**Comment by cavi21** [comment]
I think I don't fully follow the situation @ericpeters0n, sorry about it! You should think DynamoDB as a service, in that case there is no reason for a schema to be load on the test_helper.rb. I believe that what you are trying to do is to pre-load data in the DynamoDB right? if that's the case with just a something similar to `shared_context` or with a `before`, `setup` or `background` block (depending if you are using Minitest or Rspec) you should be good to go.

Is this something that's useful? or I misunderstood the hole problem?

**Comment by pboling** [comment]
There is also https://github.com/ananthakumaran/fake_dynamo though I have yet to try it.  Note that the latest version is for an API that is newer than what the official Amazon Ruby client supports.  Amazon's RUby DynamoDB client is coded against the 2011-12-05 verison of the DynamoDB API, not the slightly newer 2012-08-10 version.

Strange I know.  How many fucks does Amazon not give about Ruby?

**Comment by pboling** [comment]
This has the answer: https://github.com/Dynamoid/Dynamoid/pull/103
