### ISSUE TITLE
Dynamoid raises exception when fields which are present in Dynamodb record aren't declared in model

### ISSUE THREAD

**Issue by BilalBudhani** [Dynamoid/Dynamoid#7]
As described at https://github.com/Dynamoid/Dynamoid/pull/4#issuecomment-114946871. If there are `fields` in DynamoDB records which are not declared in Dynamoid model then, it raises exception. Ideally, It should ignore those fields and materialize the model regardlessly.

**Comment by joelpresence** [comment]
Hi,

Any progress on this?  I'm considering using this awesome gem for a Rails app talking to DynamoDB, but this concerns me - if I want to mix different record types in the same Dynamo table (why not, it's NoSQL so no schema to adhere to) then I'm afraid that this would be an issue ...

Thanks!

**Comment by philipmw** [comment]
I agree this is a problem. As far as I know, no one has started work on this issue. I'll see if I can find time, but I'd love it if someone who has more time (or has more at stake) could work on this.

**Comment by joelpresence** [comment]
I'd be happy to take a stab at it if you give me some hints where to look in the code and what to be careful of.

Thanks!

Sent from my iPhone

On Jan 4, 2016, at 6:34 PM, Philip M. White <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree this is a problem. As far as I know, no one has started work on this issue. I'll see if I can find time, but I'd love it if someone who has more time (or has more at stake) could work on this.

-

**Comment by sumocoder** [comment]
Fixed this in #33

**Comment by pboling** [comment]
@joelpresence this is fixed.  Please try latest release 1.2.1!
