### ISSUE TITLE
Getting ...uninitialized constant Item::Dynamoid....error

### ISSUE THREAD

**Issue by asit569** [Dynamoid/Dynamoid#71]
I have already installed dynamoid gem but still getting uninitialized constant error

pi@raspberrypi:~/waterpi-web $ ruby app.rb
/home/pi/waterpi-web/models/item.rb:2:in `<class:Item>': uninitialized constant Item::Dynamoid (NameError)
        from /home/pi/waterpi-web/models/item.rb:1:in `<top (required)>'
        from /home/pi/waterpi-web/boot.rb:22:in `require'
        from /home/pi/waterpi-web/boot.rb:22:in `block (2 levels) in <top (required)>'
        from /home/pi/waterpi-web/boot.rb:22:in `each'
        from /home/pi/waterpi-web/boot.rb:22:in `block in <top (required)>'
        from /home/pi/waterpi-web/boot.rb:21:in `each'
        from /home/pi/waterpi-web/boot.rb:21:in `<top (required)>'
        from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/pi/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from app.rb:3:in `<main>

souce code-  https://github.com/demirhanaydin/waterpi-web

**Comment by tayduds07** [comment]
Did you figure this out?

**Comment by pboling** [comment]
@tayduds07 This error can only happen if the Dynamoid gem hasn't been loaded.  If you are using Bundler and Rails it should be automatically loaded unless you listed the gem with `require: false`.  If using another system without Bundler autoloading, you may need to `require 'dynamoid'`.

This is not a bug in Dynamoid, it is a problem in your configuration.  Re-read the README carefully.

**Comment by tayduds07** [comment]
@pboling thank you i didn't have require 'dynamoid' but i do have include Dynamoid::Document

**Comment by tayduds07** [comment]
@asit569 I'm assuming you finished this project, how did you get the high charts to show up. I'm having a hard time getting them to show up.

**Comment by pboling** [comment]
Wrong issue tracker @tayduds07 !
