### ISSUE TITLE
Idea: "ActiveDocument"

### ISSUE THREAD

**Issue by johnnyshields** [Dynamoid/dynamoid#739]
Hi Dynamoid team, I'm a frequent contributor to Mongoid (we use it at [TableCheck](https://www.tablecheck.com/en/join/)) which I believe Dynamoid was originally forked from.

I'm wondering if there is appetite on the team here to combine efforts and create something like "ActiveDocument" which would be analogous to ActiveRecord--a DB-agnostic layer with DB-specific adapters for MongoDB and DocumentDB, possibly others like CouchDB. Just thought I would float the idea.

(Would also be open to keeping the Dynamoid name but adding multi-db support.)

**Comment by andrykonchin** [comment]
Yes, I would like to take part, at least in discussions.

**Comment by johnnyshields** [comment]
@andrykonchin very cool. What's the best forum for discussion?

**Comment by johnnyshields** [comment]
Discussion moved here: https://github.com/Dynamoid/dynamoid/discussions/741
