### ISSUE TITLE
How do I remove the timestamp fields?

### ISSUE THREAD

**Issue by JohnSmall** [Dynamoid/Dynamoid#83]
Dynamoid automatically adds the fields created_at and updated_at. But I'm reading from a table that doesn't follow Rails conventions and doesn't have those fields. How do I remove them from the table definition?

**Comment by cignoir** [comment]
There are no options to remove timestamps currently.
You can choose either one you like:
* +1 to PR #58 
* Do monkey patching refer to this commit  https://github.com/cignoir/Dynamoid/commit/6eb09aa0adefbedbd71660bc86749f0179133db8
* Use ``` gem 'dynamoid', github: 'cignoir/dynamoid', branch: 'timestamps' ``` then configure to disable timestamps.

I hope this will be of some help.

**Comment by pboling** [comment]
This has been released in 1.2.0 and 1.2.1.
