### ISSUE TITLE
eval_limit and batch don't do what I expect

### ISSUE THREAD

**Issue by JohnSmall** [Dynamoid/Dynamoid#85]
I'm not sure what the chain eval_limit and batch should do e.g. 

```
`SomeModel.eval_limit(5).batch(5)`
```

Should that get 5 records, in a batch of 5, or 5 batches of 5 records each?

When I tried it it scanned the entire table ignoring the limit.

**Comment by pboling** [comment]
@andrykonchin do you have any idea about this?

**Comment by andrykonchin** [comment]
@pboling 

`Model.where({}).eval_limit(n)` means we load first `n` items

`Model.where({}).batch(m)` means we load all matched items but internally paginate them and load `m` items at a time.

`Model.where({}).eval_limit(n).batch(m)` chain completely ignores limit `n` and works like `batch` call. But yes, I was expected behavior described by @JohnSmall too.

**Comment by pboling** [comment]
So, it is a bug 👍 , We'll leave this open to track it until we fix it.

**Comment by richardhsu** [comment]
This is updated again in https://github.com/Dynamoid/Dynamoid/pull/183 to handle scan limit as well.

**Comment by pboling** [comment]
@richardhsu so #183 doesn't fix this bug, but it adds another type of limit "support" that will be ignored if `batch` is chained?

```
Model.where({}).eval_limit(n).batch(m)
Model.where({}).scan_limit(n).batch(m)
```
Both limit types are ignored?

**Comment by richardhsu** [comment]
@pboling can you give me examples that you're seeing don't work?

I'm seeing it respect the `scan_limit` and `record_limit` and making batch queries to DynamoDB with `batch_size` assuming `batch_size < scan_limit` or `batch_size < record_limit`.

```
# Record Limit with batch of 3
> model.where({}).record_limit(5).batch(3).to_a.count
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>3}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>2, :exclusive_start_key=>{"age"=>#<BigDecimal:3e64828,'0.3E1',9(18)>, "id"=>"1"}}
=> 5

# Record limit with batch of 1
> model.where({}).record_limit(5).batch(1).to_a.count
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3ee4370,'0.1E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3f139e0,'0.2E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:1077988,'0.3E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:10413b0,'0.4E1',9(18)>, "id"=>"1"}}
=> 5

# Scan limit with batch of 1
> model.where({}).scan_limit(5).batch(1).to_a.count
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3e92fc0,'0.1E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3e150c0,'0.2E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3d9f1b8,'0.3E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3d4d2c8,'0.4E1',9(18)>, "id"=>"1"}}
=> 5

# Scan limit with batch of 2
> model.where({}).scan_limit(5).batch(2).to_a.count
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>2}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>2, :exclusive_start_key=>{"age"=>#<BigDecimal:3bff768,'0.2E1',9(18)>, "id"=>"1"}}
REQUEST {:table_name=>"dynamoid_tests_customer", :limit=>1, :exclusive_start_key=>{"age"=>#<BigDecimal:3bbb270,'0.4E1',9(18)>, "id"=>"1"}}
=> 5
```

These seem to be all expected number of requests, unless I'm misunderstanding the `batch`? (This is off `master`)

**Comment by richardhsu** [comment]
Oh, also just noticed one slight issue with `query` though that Chain isn't passing `batch_size` down to the query so I'll open up quick PR for that.

**Comment by pboling** [comment]
I was just asking if the PR actually did fix the bug, it wasn't clear to me that it did.  Looks like it is all working!

**Comment by richardhsu** [comment]
Ah, yes, sorry it does :) Will be clearer in future PR for these types of fixes!
