### ISSUE TITLE
Secondary Global Index Support

### ISSUE THREAD

**Issue by esurdam** [Dynamoid/Dynamoid#89]
What happened to support for ...

```
global_secondary_index :hash_key => :name, :range_key => :posted_at
global_secondary_index :hash_key => :length`
```

I noticed that its included in the test spec `spec/app/models/post.rb `, but I don't see it in the `Dynamoid::Document` module. 

Thanks!

**Comment by esurdam** [comment]
Found info here [#17](https://github.com/Dynamoid/Dynamoid/pull/17)

**Comment by pboling** [comment]
@esurdam Also, I have expanded support for secondary indexes here:
https://github.com/Dynamoid/Dynamoid/pull/77
