### ISSUE TITLE
Dynamoid should support DynamoDB attribute types byond string and number

### ISSUE THREAD

**Issue by philipmw** [Dynamoid/dynamoid#9]
Dynamoid translates its field types to DynamoDB attribute types, in `Dynamoid::Persistence#dynamo_type`.

The mapping right now is overly simple: all fields map either to a numeric or a string attribute. This maps container fields (`:array` and `:set`) to a string also.

AWS SDK v2 offers a better selection of attribute types that map much more closely to Dynamoid's field types. Dynamoid should support this.

Some specific ideas:
- `:array` field => List attribute
- `:set` field type should be split into `:number_set` and `:string_set` and mapped to its respective DynamoDB attribute type.

For backwards compatibility, `Persistence#undump_field` should check what value type AWS SDK returns, and undump the field using the old (string) behavior if the existing value is a string.

**Comment by sumocoder** [comment]
I am working on this. I should have something in the next 2 days.

**Comment by philipmw** [comment]
Thanks, sumocoder!

**Comment by RedaBenh** [comment]
Hi,
Do you know how to manage easily Map field (see example of 'records' field bellow )?
```
{
  "name": {
    "S": "reda dev123"
  },
  "issued_at": {
    "N": "1457278180944"
  },
  "location": {
    "S": "us-west-2"
  },
  "records": {
    "M": {
      "custom": {
        "N": "19"
      },
      "standard": {
        "N": "395"
      }
    }
  },
  "org_id": {
    "N": "1"
  }
}
```

Thanks for your help ;)

Reda

**Comment by pboling** [comment]
@sumocoder any progress on this?

**Comment by pboling** [comment]
@andrykonchin this is done now, correct?

**Comment by pboling** [comment]
@andrykonchin ping!  Did this get done already?

**Comment by RedaBenh** [comment]
Finally, i make my own custom DynamoAdapter to manage my case

**Comment by andrykonchin** [comment]
@pboling as far as I know we can use `raw` field type to store lists and maps. So yes, it's already done. Maybe we need more obvious names for field types - `list` and `map`

**Comment by baloran** [comment]
But how insert list of map with raw attributes?

**Comment by RedaBenh** [comment]
Hi @baloran
Here is some quick examples (from file : spec/dynamoid/persistence_spec.rb )

In your model

`field :config, :raw`

# it 'keeps raw Hash attributes as a Hash
--
```
config = {:acres => 5, :trees => {:cyprus => 30, :poplar => 10, :joshua => 1}, :horses => ['Lucky', 'Dummy'], :lake => 1, :tennis_court => 1}
@addr = Address.new(:config => config)
# OR
# keeps raw Array attributes as an Array
config = ['windows', 'roof', 'doors']
@addr = Address.new(:config => config)
```

**Comment by pboling** [comment]
So we just need to document this support better in the Readme perhaps.

**Comment by psulightning** [comment]
bump: should support Map type like @RedaBenh stated

**Comment by andrykonchin** [comment]
@psulightning Doesn't `:raw` type work for you well for storing field as a DynamoDB's `Map` attribute?

**Comment by psulightning** [comment]
Is that indicated in the documentation?  Does `:raw` basically just hand off to the DynamoDB::Client and let it figure out what to do?

**Comment by andrykonchin** [comment]
@psulightning It's just a shortcut for "anything that is mapped to DynamoDB types automatically".

I am curious what you mean when say about supporting of `Map` type? What do you expect from this support?

**Comment by patrykk21** [comment]
Is this a dead issue? This seems correctly implemented in latest versions.

**Comment by andrykonchin** [comment]
Hmm, looks like you are right.

There are `set`, `array` and `map` field types. And the original issue in this thread could be solved with `raw` field type.
