### ISSUE TITLE
Error while migrating from dynamoid 0.6 to 1.1

### ISSUE THREAD

**Issue by raunaklakhwani** [Dynamoid/Dynamoid#91]
Hi,

I am getting the below error while querying the dynamodb database.

**expected hash value for member 1 of key attribute_value_list of value at key is_submitted of option scan_filter**

I have recently migrated from dynamoid 0.6 to 1.1.

I am getting this error on line.

**Node.where(:is_submitted => 't').where(:is_signed_off => 'f').count**

Node is the model in rails application.

Below is the stack trace : 

> aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:337:in `validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:245:in `block in validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:243:in `each'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:243:in `validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:346:in `block in validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:342:in `each'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:342:in `validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:410:in `block in validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:408:in `each'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:408:in `validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:590:in `block in validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:586:in `each'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:586:in `validate'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:611:in `to_h'
aws-sdk (1.20.0) lib/aws/core/option_grammar.rb:621:in `to_json'
aws-sdk (1.20.0) lib/aws/core/json_request_builder.rb:29:in `populate_request'
aws-sdk (1.20.0) lib/aws/core/client.rb:704:in `block (2 levels) in define_client_method'
aws-sdk (1.20.0) lib/aws/core/client.rb:549:in `build_request'
aws-sdk (1.20.0) lib/aws/core/client.rb:482:in `block (3 levels) in client_request'
aws-sdk (1.20.0) lib/aws/core/response.rb:171:in `call'
aws-sdk (1.20.0) lib/aws/core/response.rb:171:in `build_request'
aws-sdk (1.20.0) lib/aws/core/response.rb:111:in `initialize'
aws-sdk (1.20.0) lib/aws/core/client.rb:195:in `new'
aws-sdk (1.20.0) lib/aws/core/client.rb:195:in `new_response'
aws-sdk (1.20.0) lib/aws/core/client.rb:481:in `block (2 levels) in client_request'
aws-sdk (1.20.0) lib/aws/core/client.rb:382:in `log_client_request'
aws-sdk (1.20.0) lib/aws/core/client.rb:468:in `block in client_request'
aws-sdk (1.20.0) lib/aws/core/client.rb:364:in `return_or_raise'
aws-sdk (1.20.0) lib/aws/core/client.rb:467:in `client_request'
(eval):3:in `scan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:368:in `block (2 levels) in scan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:367:in `loop'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:367:in `block in scan'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `block in records_via_scan'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `to_a'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `Array'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `records'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:95:in `each'
app/controllers/application_controller.rb:106:in `count'
app/controllers/application_controller.rb:106:in `set_global_counts'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:143:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:501:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:501:in `block in call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:501:in `each'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:501:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.1.14.2) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.14.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.14.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/cookies.rb:562:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.53/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.53/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.14.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
railties (4.1.14.2) lib/rails/application.rb:144:in `call'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `method_missing'
rack (1.5.2) lib/rack/lint.rb:49:in `_call'
rack (1.5.2) lib/rack/lint.rb:37:in `call'
rack (1.5.2) lib/rack/showexceptions.rb:24:in `call'
rack (1.5.2) lib/rack/commonlogger.rb:33:in `call'
rack (1.5.2) lib/rack/chunked.rb:43:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:138:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:94:in `run'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/server.rb:191:in `block in start_thread'

Can anyone help me in this?

**Comment by cavi21** [comment]
Hi! this issue is due to a similar situation that I mention on the other issue of yours [#70 Migration from Dynamoid 0.7 to 1.1.0](https://github.com/Dynamoid/Dynamoid/issues/90) but in this case I have a ***non-supported*** version of `aws-sdk` running along with `dynamoid 1.1.0`, you can see this in your stack trace:
```log
[...]
aws-sdk (1.20.0) lib/aws/core/client.rb:467:in client_request' (eval):3:inscan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:368
[...]
```
and as states in the [prerequisites](https://github.com/Dynamoid/Dynamoid#prerequisities) **NOTE**:

> NOTE: Dynamoid-1.0 doesn't support aws-sdk Version 1 (Use Dynamoid Major Version 0 for aws-sdk 1)

So if you need to stick to was-sdk v1.x you will need to run Dynamoid 0.x as you was doing.

Hope this helps
