### ISSUE TITLE
Looks like gem version (ruby gems) 1.1.0 is outdated.

### ISSUE THREAD

**Issue by munish-spokeo** [Dynamoid/Dynamoid#94]
Looks like gem version (ruby gems) 1.1.0 is outdated. It does not support indexes and was built in Dec'2015. Can we update the gem?

**Comment by cignoir** [comment]
This causes another issue like #78. I hope to be updated too.

**Comment by munish-spokeo** [comment]
Is this gem is maintained anymore?

**Comment by pboling** [comment]
2 new maintainers were added 3 days ago, and we are working on a new version.  It did go through a period of almost-no-maintenance though.
Assistance is certainly welcome!  Right now I am struggling with getting Travis passing.  It seems to be a very fickle build.

**Comment by cavi21** [comment]
Hi @pboling I deal with it a time ago, and I was able to narrow down to an issue on some memory limitations on the travis-ci VMs, I mention them in this other [PR #77](https://github.com/Dynamoid/Dynamoid/pull/77) and I'm happy to help on anything I can or if it's useful?

Let me know how do you want to do that?

**Comment by bglusman** [comment]
@cavi21 thanks!  Peter and I are the two new maintainers, but I haven't had a chance to do much yet...  @pboling do you think we can resolve the #77 test issues soon and should wait a few days for a release to include that, or perhaps just release current master as 1.2.0 and include #77 when ready as 1.2.1 perhaps?

**Comment by pboling** [comment]
Test issues are resolved.  Version 1.2.0 is released.
