### ISSUE TITLE
Dynamoid::Criteria::Chain uses Enumerable#first for find by resulting in scan even if index is present

### ISSUE THREAD

**Issue by bglusman** [Dynamoid/dynamoid#96]
We discovered this quite unpleasantly via accidentally hitting Dynamoid::Finders#method_missing when a refactor failed to configure some custom find_by methods under certain circumstances not caught by our test suite, but it seems like we can probably refactor this to use indexes when the find by is on an indexed attribute, if we define Dynamoid::Criteria::Chain#first to reflect on indexes and do `find_all_by_secondary_index(chain.query).first` or something to that effect.  Possibly we can also add a config option to error instead of falling back on Enumerable#first if the indexes don't exist, as that may be preferable to doing a full table scan.

**Comment by andrykonchin** [comment]
`.first` method is optimized to limit scanned items here https://github.com/Dynamoid/dynamoid/pull/440.
