### ISSUE TITLE
Undefined method error on `index`

### ISSUE THREAD

**Issue by archonic** [Dynamoid/Dynamoid#97]
The console message instructing what to add to my class to index had bad syntax.

    You can index this query by adding this to notificationeventemail.rb: index [:[:body, {:type=>:string}], :[:created_at, {:type=>:datetime}], :[:id, {:type=>:string}], :[:instant, {:type=>:boolean}], :[:notification_generator_id, {:type=>:integer}], :[:recipient, {:type=>:string}], :[:subject, {:type=>:string}], :[:updated_at, {:type=>:datetime}]]

I took a look at the docs, but now I'm getting a no method error for `index`.

    RuntimeError: Error creating email notification: undefined method `index' for NotificationEventEmail:Class | ["/Users/whatever/.rvm/gems/ruby-2.0.0-p451@itglue/gems/dynamoid-1.1.0/lib/dynamoid/finders.rb:128:in `method_missing'

In my class I've just got:

    index [:instant, :notification_generator_id, :recipient, :subject, :body]

**Comment by pboling** [comment]
Are you using the latest released version, or the master branch?  The advise on how to index is in fact incorrect.  You will probably need to setup secondary indexes if you want to query by non-primary keys.

**Comment by archonic** [comment]
In this particular case, I was querying by all attributes except id, created_at and updated_at to determine if there were duplicate records before saving. I should instead be using [updateItem](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) for that. It looks like that was [left out](https://github.com/Dynamoid/Dynamoid/blob/5dfff232e57688d083b591d5ac3631b2afebab25/spec/dynamoid/adapter_plugin/aws_sdk_v2_spec.rb#L385). Any chance a new release will accommodate that?

I'll still need to be able to index attributes for a separate search log table feature. Let me know if I can help with anything. Dynamoid is enabling a fairly large and important feature which is launching soon, so thanks for your hard work!

**Comment by pboling** [comment]
@archonic It is unlikely that any support will be added for any features unless you add them yourself.  This project is built by people who are building the features they are using for narrow use cases.

I would recommend looking around the network view and see if anyone else has worked on `updateItem`.

**Comment by archonic** [comment]
I'll have a look around for `updateItem` and write it in if I don't see it.

Getting back to the topic, is there up to date documentation on the syntax of indexing (or secondary indexing), or is that unreleased?

**Comment by pboling** [comment]
I added support for secondary indexes in my fork.  Have a look at pboling/master.  I only understand it well enough to get it working, and based my work on the work of others already done.    Unfortunately I won't be of much help, but perhaps the secondary index implementation can serve as a template for what you want to accomplish.

**Comment by pboling** [comment]
@archonic secondary index support has been merged to master.

Also the persistence layer has `def update!(conditions = {}, &block)` which calls the adapter's `def update_item(table_name, key, options = {})`.  You might try using one of those?
