### ISSUE TITLE
DynamoDB With Ruby ON Rails

### ISSUE THREAD

**Issue by raunaklakhwani** [Dynamoid/Dynamoid#99]
HI,

I am having a rails application with dynamodb as database.
Ruby : 1.9.1
Ruby On Rails : 4.1
DynamoDB : 1.1

I am getting this error : 

> /home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/set.rb:85:in `do_with_enum'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/set.rb:310:in `merge'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/set.rb:75:in `initialize'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:99:in `new'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:99:in `undump_field'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:61:in `block (2 levels) in undump'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:60:in `each'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:60:in `block in undump'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:59:in `tap'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:59:in `undump'
dynamoid (1.1.0) lib/dynamoid/document.rb:133:in `load'
dynamoid (1.1.0) lib/dynamoid/document.rb:128:in `block in initialize'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
dynamoid (1.1.0) lib/dynamoid/document.rb:123:in `initialize'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:51:in `new'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:51:in `from_database'
dynamoid (1.1.0) lib/dynamoid/identity_map.rb:15:in `from_database'
dynamoid (1.1.0) lib/dynamoid/dirty.rb:8:in `from_database'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:143:in `block (2 levels) in records_via_scan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:370:in `<<'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:370:in `block (3 levels) in scan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:370:in `each'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:370:in `block (2 levels) in scan'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:367:in `loop'
dynamoid (1.1.0) lib/dynamoid/adapter_plugin/aws_sdk_v2.rb:367:in `block in scan'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:142:in `block in records_via_scan'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `each'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `to_a'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `Array'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:115:in `records'
dynamoid (1.1.0) lib/dynamoid/criteria/chain.rb:46:in `all'
app/models/node.rb:931:in `all_non_confidential_worldwide'
lib/brazil_config_helper.rb:162:in `get_node_names'
app/views/tabs/_site_information_fields.html.slim:49:in `_app_views_tabs__site_information_fields_html_slim__1161341738563972731_69854304393120'
actionview (4.1.14.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.14.2) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:143:in `render'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:278:in `render'
actionview (4.1.14.2) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.1.14.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
haml (4.0.0) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
app/views/tabs/_read_only_form.html.slim:11:in `block in _app_views_tabs__read_only_form_html_slim___379420859086536323_69853819859700'
app/views/tabs/_read_only_form.html.slim:8:in `each'
app/views/tabs/_read_only_form.html.slim:8:in `_app_views_tabs__read_only_form_html_slim___379420859086536323_69853819859700'
actionview (4.1.14.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.14.2) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:143:in `render'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/partial_renderer.rb:278:in `render'
actionview (4.1.14.2) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.1.14.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
haml (4.0.0) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
app/views/tabs/show.html.slim:7:in `block in _app_views_tabs_show_html_slim___2573104391332512245_69853756219540'
actionview (4.1.14.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.1.14.2) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.0) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.1.14.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.0) lib/haml/helpers/action_view_mods.rb:59:in `capture_with_haml'
actionview (4.1.14.2) lib/action_view/helpers/form_helper.rb:434:in `form_for'
haml (4.0.0) lib/haml/helpers/action_view_mods.rb:135:in `form_for_with_haml'
haml (4.0.0) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
app/views/tabs/show.html.slim:6:in `_app_views_tabs_show_html_slim___2573104391332512245_69853756219540'
actionview (4.1.14.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.14.2) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.14.2) lib/action_view/template.rb:143:in `render'
actionview (4.1.14.2) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.14.2) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
actionview (4.1.14.2) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
actionview (4.1.14.2) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
actionview (4.1.14.2) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionview (4.1.14.2) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.1.14.2) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.1.14.2) lib/action_view/rendering.rb:99:in `_render_template'
actionpack (4.1.14.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.1.14.2) lib/action_view/rendering.rb:82:in `render_to_body'
actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.1.14.2) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
actionpack (4.1.14.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.1.14.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/benchmark.rb:295:in `realtime'
activesupport (4.1.14.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
app/controllers/nodes_controller.rb:43:in `block (2 levels) in show'
actionpack (4.1.14.2) lib/action_controller/metal/mime_responds.rb:258:in `call'
actionpack (4.1.14.2) lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
app/controllers/nodes_controller.rb:42:in `show'
actionpack (4.1.14.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.14.2) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.1.14.2) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.14.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.14.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/cookies.rb:562:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.62/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.62/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.14.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
railties (4.1.14.2) lib/rails/application.rb:144:in `call'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `method_missing'
rack (1.5.2) lib/rack/lint.rb:49:in `_call'
rack (1.5.2) lib/rack/lint.rb:37:in `call'
rack (1.5.2) lib/rack/showexceptions.rb:24:in `call'
rack (1.5.2) lib/rack/commonlogger.rb:33:in `call'
rack (1.5.2) lib/rack/chunked.rb:43:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:138:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:94:in `run'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/server.rb:191:in `block in start_thread'

The error is in this line : 

    Node.where(:is_confidential => 'f').all 

Can anyone help me in this?

**Comment by pboling** [comment]
1. Upgrade to at minimum Ruby 1.9.3
2. Install just released version of the gem, 1.2.1.
3. Try again.  Then report back if it still fails.
